/* eslint-disable */
import {
  CollectionCustomizer,
  TAggregation,
  TConditionTree,
  TPaginatedFilter,
  TPartialRow,
  TSortClause
} from '@forestadmin/agent';

export type ActivitiesCustomizer = CollectionCustomizer<Schema, 'activities'>;
export type ActivitiesRecord = TPartialRow<Schema, 'activities'>;
export type ActivitiesConditionTree = TConditionTree<Schema, 'activities'>;
export type ActivitiesFilter = TPaginatedFilter<Schema, 'activities'>;
export type ActivitiesSortClause = TSortClause<Schema, 'activities'>;
export type ActivitiesAggregation = TAggregation<Schema, 'activities'>;

export type CompaniesCustomizer = CollectionCustomizer<Schema, 'companies'>;
export type CompaniesRecord = TPartialRow<Schema, 'companies'>;
export type CompaniesConditionTree = TConditionTree<Schema, 'companies'>;
export type CompaniesFilter = TPaginatedFilter<Schema, 'companies'>;
export type CompaniesSortClause = TSortClause<Schema, 'companies'>;
export type CompaniesAggregation = TAggregation<Schema, 'companies'>;

export type FeaturesCustomizer = CollectionCustomizer<Schema, 'features'>;
export type FeaturesRecord = TPartialRow<Schema, 'features'>;
export type FeaturesConditionTree = TConditionTree<Schema, 'features'>;
export type FeaturesFilter = TPaginatedFilter<Schema, 'features'>;
export type FeaturesSortClause = TSortClause<Schema, 'features'>;
export type FeaturesAggregation = TAggregation<Schema, 'features'>;

export type InvoicesCustomizer = CollectionCustomizer<Schema, 'invoices'>;
export type InvoicesRecord = TPartialRow<Schema, 'invoices'>;
export type InvoicesConditionTree = TConditionTree<Schema, 'invoices'>;
export type InvoicesFilter = TPaginatedFilter<Schema, 'invoices'>;
export type InvoicesSortClause = TSortClause<Schema, 'invoices'>;
export type InvoicesAggregation = TAggregation<Schema, 'invoices'>;

export type PlansCustomizer = CollectionCustomizer<Schema, 'plans'>;
export type PlansRecord = TPartialRow<Schema, 'plans'>;
export type PlansConditionTree = TConditionTree<Schema, 'plans'>;
export type PlansFilter = TPaginatedFilter<Schema, 'plans'>;
export type PlansSortClause = TSortClause<Schema, 'plans'>;
export type PlansAggregation = TAggregation<Schema, 'plans'>;

export type SubscriptionsCustomizer = CollectionCustomizer<Schema, 'subscriptions'>;
export type SubscriptionsRecord = TPartialRow<Schema, 'subscriptions'>;
export type SubscriptionsConditionTree = TConditionTree<Schema, 'subscriptions'>;
export type SubscriptionsFilter = TPaginatedFilter<Schema, 'subscriptions'>;
export type SubscriptionsSortClause = TSortClause<Schema, 'subscriptions'>;
export type SubscriptionsAggregation = TAggregation<Schema, 'subscriptions'>;

export type SupportTicketsCustomizer = CollectionCustomizer<Schema, 'support_tickets'>;
export type SupportTicketsRecord = TPartialRow<Schema, 'support_tickets'>;
export type SupportTicketsConditionTree = TConditionTree<Schema, 'support_tickets'>;
export type SupportTicketsFilter = TPaginatedFilter<Schema, 'support_tickets'>;
export type SupportTicketsSortClause = TSortClause<Schema, 'support_tickets'>;
export type SupportTicketsAggregation = TAggregation<Schema, 'support_tickets'>;

export type TransactionsCustomizer = CollectionCustomizer<Schema, 'transactions'>;
export type TransactionsRecord = TPartialRow<Schema, 'transactions'>;
export type TransactionsConditionTree = TConditionTree<Schema, 'transactions'>;
export type TransactionsFilter = TPaginatedFilter<Schema, 'transactions'>;
export type TransactionsSortClause = TSortClause<Schema, 'transactions'>;
export type TransactionsAggregation = TAggregation<Schema, 'transactions'>;

export type UsersCustomizer = CollectionCustomizer<Schema, 'users'>;
export type UsersRecord = TPartialRow<Schema, 'users'>;
export type UsersConditionTree = TConditionTree<Schema, 'users'>;
export type UsersFilter = TPaginatedFilter<Schema, 'users'>;
export type UsersSortClause = TSortClause<Schema, 'users'>;
export type UsersAggregation = TAggregation<Schema, 'users'>;


export type Schema = {
  'activities': {
    plain: {
      'company_id': number;
      'customer_id': number;
      'feature_id': number;
      'id': number;
      'logged_at': string;
    };
    nested: {
      'company': Schema['companies']['plain'] & Schema['companies']['nested'];
      'customer': Schema['users']['plain'] & Schema['users']['nested'];
      'feature': Schema['features']['plain'] & Schema['features']['nested'];
    };
    flat: {
      'company:created_at': string;
      'company:id': number;
      'company:industry': string | null;
      'company:MRR': number | null;
      'company:name': string;
      'company:nbUsers': number | null;
      'company:planId': number | null;
      'company:planPrice': number | null;
      'company:size': number | null;
      'company:updated_at': string;
      'company:user_id': number | null;
      'customer:avatar': string | null;
      'customer:company_id': number | null;
      'customer:completed_at': string | null;
      'customer:created_at': string;
      'customer:email': string;
      'customer:firstname': string;
      'customer:Fullname': string | null;
      'customer:id': number;
      'customer:lastname': string;
      'customer:password': string;
      'customer:role': 'admin' | 'editor' | 'user';
      'customer:status': 'deleted' | 'disabled' | 'enabled';
      'customer:updated_at': string;
      'feature:created_at': string;
      'feature:description': string | null;
      'feature:id': number;
      'feature:name': string;
      'feature:plan_enterprise': boolean;
      'feature:plan_free': boolean;
      'feature:plan_pro': boolean;
      'feature:plan_team': boolean;
      'feature:updated_at': string;
      'company:currentPlan:created_at': string;
      'company:currentPlan:description': string | null;
      'company:currentPlan:id': number;
      'company:currentPlan:interval': 'custom' | 'monthly' | 'yearly';
      'company:currentPlan:name': string;
      'company:currentPlan:price': number;
      'company:currentPlan:updated_at': string;
      'company:user:avatar': string | null;
      'company:user:company_id': number | null;
      'company:user:completed_at': string | null;
      'company:user:created_at': string;
      'company:user:email': string;
      'company:user:firstname': string;
      'company:user:Fullname': string | null;
      'company:user:id': number;
      'company:user:lastname': string;
      'company:user:password': string;
      'company:user:role': 'admin' | 'editor' | 'user';
      'company:user:status': 'deleted' | 'disabled' | 'enabled';
      'company:user:updated_at': string;
      'customer:company:created_at': string;
      'customer:company:id': number;
      'customer:company:industry': string | null;
      'customer:company:MRR': number | null;
      'customer:company:name': string;
      'customer:company:nbUsers': number | null;
      'customer:company:planId': number | null;
      'customer:company:planPrice': number | null;
      'customer:company:size': number | null;
      'customer:company:updated_at': string;
      'customer:company:user_id': number | null;
      'company:user:company:created_at': string;
      'company:user:company:id': number;
      'company:user:company:industry': string | null;
      'company:user:company:MRR': number | null;
      'company:user:company:name': string;
      'company:user:company:nbUsers': number | null;
      'company:user:company:planId': number | null;
      'company:user:company:planPrice': number | null;
      'company:user:company:size': number | null;
      'company:user:company:updated_at': string;
      'company:user:company:user_id': number | null;
      'customer:company:currentPlan:created_at': string;
      'customer:company:currentPlan:description': string | null;
      'customer:company:currentPlan:id': number;
      'customer:company:currentPlan:interval': 'custom' | 'monthly' | 'yearly';
      'customer:company:currentPlan:name': string;
      'customer:company:currentPlan:price': number;
      'customer:company:currentPlan:updated_at': string;
      'customer:company:user:avatar': string | null;
      'customer:company:user:company_id': number | null;
      'customer:company:user:completed_at': string | null;
      'customer:company:user:created_at': string;
      'customer:company:user:email': string;
      'customer:company:user:firstname': string;
      'customer:company:user:Fullname': string | null;
      'customer:company:user:id': number;
      'customer:company:user:lastname': string;
      'customer:company:user:password': string;
      'customer:company:user:role': 'admin' | 'editor' | 'user';
      'customer:company:user:status': 'deleted' | 'disabled' | 'enabled';
      'customer:company:user:updated_at': string;
      'company:user:company:currentPlan:created_at': string;
      'company:user:company:currentPlan:description': string | null;
      'company:user:company:currentPlan:id': number;
      'company:user:company:currentPlan:interval': 'custom' | 'monthly' | 'yearly';
      'company:user:company:currentPlan:name': string;
      'company:user:company:currentPlan:price': number;
      'company:user:company:currentPlan:updated_at': string;
      'company:user:company:user:avatar': string | null;
      'company:user:company:user:company_id': number | null;
      'company:user:company:user:completed_at': string | null;
      'company:user:company:user:created_at': string;
      'company:user:company:user:email': string;
      'company:user:company:user:firstname': string;
      'company:user:company:user:Fullname': string | null;
      'company:user:company:user:id': number;
      'company:user:company:user:lastname': string;
      'company:user:company:user:password': string;
      'company:user:company:user:role': 'admin' | 'editor' | 'user';
      'company:user:company:user:status': 'deleted' | 'disabled' | 'enabled';
      'company:user:company:user:updated_at': string;
      'customer:company:user:company:created_at': string;
      'customer:company:user:company:id': number;
      'customer:company:user:company:industry': string | null;
      'customer:company:user:company:MRR': number | null;
      'customer:company:user:company:name': string;
      'customer:company:user:company:nbUsers': number | null;
      'customer:company:user:company:planId': number | null;
      'customer:company:user:company:planPrice': number | null;
      'customer:company:user:company:size': number | null;
      'customer:company:user:company:updated_at': string;
      'customer:company:user:company:user_id': number | null;
      'company:user:company:user:company:created_at': string;
      'company:user:company:user:company:id': number;
      'company:user:company:user:company:industry': string | null;
      'company:user:company:user:company:MRR': number | null;
      'company:user:company:user:company:name': string;
      'company:user:company:user:company:nbUsers': number | null;
      'company:user:company:user:company:planId': number | null;
      'company:user:company:user:company:planPrice': number | null;
      'company:user:company:user:company:size': number | null;
      'company:user:company:user:company:updated_at': string;
      'company:user:company:user:company:user_id': number | null;
      'customer:company:user:company:currentPlan:created_at': string;
      'customer:company:user:company:currentPlan:description': string | null;
      'customer:company:user:company:currentPlan:id': number;
      'customer:company:user:company:currentPlan:interval': 'custom' | 'monthly' | 'yearly';
      'customer:company:user:company:currentPlan:name': string;
      'customer:company:user:company:currentPlan:price': number;
      'customer:company:user:company:currentPlan:updated_at': string;
      'customer:company:user:company:user:avatar': string | null;
      'customer:company:user:company:user:company_id': number | null;
      'customer:company:user:company:user:completed_at': string | null;
      'customer:company:user:company:user:created_at': string;
      'customer:company:user:company:user:email': string;
      'customer:company:user:company:user:firstname': string;
      'customer:company:user:company:user:Fullname': string | null;
      'customer:company:user:company:user:id': number;
      'customer:company:user:company:user:lastname': string;
      'customer:company:user:company:user:password': string;
      'customer:company:user:company:user:role': 'admin' | 'editor' | 'user';
      'customer:company:user:company:user:status': 'deleted' | 'disabled' | 'enabled';
      'customer:company:user:company:user:updated_at': string;
    };
  };
  'companies': {
    plain: {
      'created_at': string;
      'id': number;
      'industry': string | null;
      'MRR': number | null;
      'name': string;
      'nbUsers': number | null;
      'planId': number | null;
      'planPrice': number | null;
      'size': number | null;
      'updated_at': string;
      'user_id': number | null;
    };
    nested: {
      'currentPlan': Schema['plans']['plain'] & Schema['plans']['nested'];
      'user': Schema['users']['plain'] & Schema['users']['nested'];
    };
    flat: {
      'currentPlan:created_at': string;
      'currentPlan:description': string | null;
      'currentPlan:id': number;
      'currentPlan:interval': 'custom' | 'monthly' | 'yearly';
      'currentPlan:name': string;
      'currentPlan:price': number;
      'currentPlan:updated_at': string;
      'user:avatar': string | null;
      'user:company_id': number | null;
      'user:completed_at': string | null;
      'user:created_at': string;
      'user:email': string;
      'user:firstname': string;
      'user:Fullname': string | null;
      'user:id': number;
      'user:lastname': string;
      'user:password': string;
      'user:role': 'admin' | 'editor' | 'user';
      'user:status': 'deleted' | 'disabled' | 'enabled';
      'user:updated_at': string;
      'user:company:created_at': string;
      'user:company:id': number;
      'user:company:industry': string | null;
      'user:company:MRR': number | null;
      'user:company:name': string;
      'user:company:nbUsers': number | null;
      'user:company:planId': number | null;
      'user:company:planPrice': number | null;
      'user:company:size': number | null;
      'user:company:updated_at': string;
      'user:company:user_id': number | null;
      'user:company:currentPlan:created_at': string;
      'user:company:currentPlan:description': string | null;
      'user:company:currentPlan:id': number;
      'user:company:currentPlan:interval': 'custom' | 'monthly' | 'yearly';
      'user:company:currentPlan:name': string;
      'user:company:currentPlan:price': number;
      'user:company:currentPlan:updated_at': string;
      'user:company:user:avatar': string | null;
      'user:company:user:company_id': number | null;
      'user:company:user:completed_at': string | null;
      'user:company:user:created_at': string;
      'user:company:user:email': string;
      'user:company:user:firstname': string;
      'user:company:user:Fullname': string | null;
      'user:company:user:id': number;
      'user:company:user:lastname': string;
      'user:company:user:password': string;
      'user:company:user:role': 'admin' | 'editor' | 'user';
      'user:company:user:status': 'deleted' | 'disabled' | 'enabled';
      'user:company:user:updated_at': string;
      'user:company:user:company:created_at': string;
      'user:company:user:company:id': number;
      'user:company:user:company:industry': string | null;
      'user:company:user:company:MRR': number | null;
      'user:company:user:company:name': string;
      'user:company:user:company:nbUsers': number | null;
      'user:company:user:company:planId': number | null;
      'user:company:user:company:planPrice': number | null;
      'user:company:user:company:size': number | null;
      'user:company:user:company:updated_at': string;
      'user:company:user:company:user_id': number | null;
      'user:company:user:company:currentPlan:created_at': string;
      'user:company:user:company:currentPlan:description': string | null;
      'user:company:user:company:currentPlan:id': number;
      'user:company:user:company:currentPlan:interval': 'custom' | 'monthly' | 'yearly';
      'user:company:user:company:currentPlan:name': string;
      'user:company:user:company:currentPlan:price': number;
      'user:company:user:company:currentPlan:updated_at': string;
      'user:company:user:company:user:avatar': string | null;
      'user:company:user:company:user:company_id': number | null;
      'user:company:user:company:user:completed_at': string | null;
      'user:company:user:company:user:created_at': string;
      'user:company:user:company:user:email': string;
      'user:company:user:company:user:firstname': string;
      'user:company:user:company:user:Fullname': string | null;
      'user:company:user:company:user:id': number;
      'user:company:user:company:user:lastname': string;
      'user:company:user:company:user:password': string;
      'user:company:user:company:user:role': 'admin' | 'editor' | 'user';
      'user:company:user:company:user:status': 'deleted' | 'disabled' | 'enabled';
      'user:company:user:company:user:updated_at': string;
    };
  };
  'features': {
    plain: {
      'created_at': string;
      'description': string | null;
      'id': number;
      'name': string;
      'plan_enterprise': boolean;
      'plan_free': boolean;
      'plan_pro': boolean;
      'plan_team': boolean;
      'updated_at': string;
    };
    nested: {};
    flat: {};
  };
  'invoices': {
    plain: {
      'amount': number;
      'company_id': number;
      'created_at': string;
      'customer_id': number;
      'id': number;
      'plan_id': number;
      'status': 'paid' | 'pending' | 'void';
      'subscription_id': number;
      'updated_at': string;
    };
    nested: {
      'company': Schema['companies']['plain'] & Schema['companies']['nested'];
      'customer': Schema['users']['plain'] & Schema['users']['nested'];
      'plan': Schema['plans']['plain'] & Schema['plans']['nested'];
      'subscription': Schema['subscriptions']['plain'] & Schema['subscriptions']['nested'];
    };
    flat: {
      'company:created_at': string;
      'company:id': number;
      'company:industry': string | null;
      'company:MRR': number | null;
      'company:name': string;
      'company:nbUsers': number | null;
      'company:planId': number | null;
      'company:planPrice': number | null;
      'company:size': number | null;
      'company:updated_at': string;
      'company:user_id': number | null;
      'customer:avatar': string | null;
      'customer:company_id': number | null;
      'customer:completed_at': string | null;
      'customer:created_at': string;
      'customer:email': string;
      'customer:firstname': string;
      'customer:Fullname': string | null;
      'customer:id': number;
      'customer:lastname': string;
      'customer:password': string;
      'customer:role': 'admin' | 'editor' | 'user';
      'customer:status': 'deleted' | 'disabled' | 'enabled';
      'customer:updated_at': string;
      'plan:created_at': string;
      'plan:description': string | null;
      'plan:id': number;
      'plan:interval': 'custom' | 'monthly' | 'yearly';
      'plan:name': string;
      'plan:price': number;
      'plan:updated_at': string;
      'subscription:commitment': 'monthly' | 'yearly';
      'subscription:company_id': number;
      'subscription:created_at': string;
      'subscription:customer_id': number;
      'subscription:discount': number | null;
      'subscription:ended_at': string | null;
      'subscription:id': number;
      'subscription:plan_id': number;
      'subscription:renewal_date': string | null;
      'subscription:started_at': string;
      'subscription:status': 'active' | 'canceled' | 'paused';
      'subscription:updated_at': string;
      'company:currentPlan:created_at': string;
      'company:currentPlan:description': string | null;
      'company:currentPlan:id': number;
      'company:currentPlan:interval': 'custom' | 'monthly' | 'yearly';
      'company:currentPlan:name': string;
      'company:currentPlan:price': number;
      'company:currentPlan:updated_at': string;
      'company:user:avatar': string | null;
      'company:user:company_id': number | null;
      'company:user:completed_at': string | null;
      'company:user:created_at': string;
      'company:user:email': string;
      'company:user:firstname': string;
      'company:user:Fullname': string | null;
      'company:user:id': number;
      'company:user:lastname': string;
      'company:user:password': string;
      'company:user:role': 'admin' | 'editor' | 'user';
      'company:user:status': 'deleted' | 'disabled' | 'enabled';
      'company:user:updated_at': string;
      'customer:company:created_at': string;
      'customer:company:id': number;
      'customer:company:industry': string | null;
      'customer:company:MRR': number | null;
      'customer:company:name': string;
      'customer:company:nbUsers': number | null;
      'customer:company:planId': number | null;
      'customer:company:planPrice': number | null;
      'customer:company:size': number | null;
      'customer:company:updated_at': string;
      'customer:company:user_id': number | null;
      'subscription:company:created_at': string;
      'subscription:company:id': number;
      'subscription:company:industry': string | null;
      'subscription:company:MRR': number | null;
      'subscription:company:name': string;
      'subscription:company:nbUsers': number | null;
      'subscription:company:planId': number | null;
      'subscription:company:planPrice': number | null;
      'subscription:company:size': number | null;
      'subscription:company:updated_at': string;
      'subscription:company:user_id': number | null;
      'subscription:customer:avatar': string | null;
      'subscription:customer:company_id': number | null;
      'subscription:customer:completed_at': string | null;
      'subscription:customer:created_at': string;
      'subscription:customer:email': string;
      'subscription:customer:firstname': string;
      'subscription:customer:Fullname': string | null;
      'subscription:customer:id': number;
      'subscription:customer:lastname': string;
      'subscription:customer:password': string;
      'subscription:customer:role': 'admin' | 'editor' | 'user';
      'subscription:customer:status': 'deleted' | 'disabled' | 'enabled';
      'subscription:customer:updated_at': string;
      'subscription:plan:created_at': string;
      'subscription:plan:description': string | null;
      'subscription:plan:id': number;
      'subscription:plan:interval': 'custom' | 'monthly' | 'yearly';
      'subscription:plan:name': string;
      'subscription:plan:price': number;
      'subscription:plan:updated_at': string;
      'company:user:company:created_at': string;
      'company:user:company:id': number;
      'company:user:company:industry': string | null;
      'company:user:company:MRR': number | null;
      'company:user:company:name': string;
      'company:user:company:nbUsers': number | null;
      'company:user:company:planId': number | null;
      'company:user:company:planPrice': number | null;
      'company:user:company:size': number | null;
      'company:user:company:updated_at': string;
      'company:user:company:user_id': number | null;
      'customer:company:currentPlan:created_at': string;
      'customer:company:currentPlan:description': string | null;
      'customer:company:currentPlan:id': number;
      'customer:company:currentPlan:interval': 'custom' | 'monthly' | 'yearly';
      'customer:company:currentPlan:name': string;
      'customer:company:currentPlan:price': number;
      'customer:company:currentPlan:updated_at': string;
      'customer:company:user:avatar': string | null;
      'customer:company:user:company_id': number | null;
      'customer:company:user:completed_at': string | null;
      'customer:company:user:created_at': string;
      'customer:company:user:email': string;
      'customer:company:user:firstname': string;
      'customer:company:user:Fullname': string | null;
      'customer:company:user:id': number;
      'customer:company:user:lastname': string;
      'customer:company:user:password': string;
      'customer:company:user:role': 'admin' | 'editor' | 'user';
      'customer:company:user:status': 'deleted' | 'disabled' | 'enabled';
      'customer:company:user:updated_at': string;
      'subscription:company:currentPlan:created_at': string;
      'subscription:company:currentPlan:description': string | null;
      'subscription:company:currentPlan:id': number;
      'subscription:company:currentPlan:interval': 'custom' | 'monthly' | 'yearly';
      'subscription:company:currentPlan:name': string;
      'subscription:company:currentPlan:price': number;
      'subscription:company:currentPlan:updated_at': string;
      'subscription:company:user:avatar': string | null;
      'subscription:company:user:company_id': number | null;
      'subscription:company:user:completed_at': string | null;
      'subscription:company:user:created_at': string;
      'subscription:company:user:email': string;
      'subscription:company:user:firstname': string;
      'subscription:company:user:Fullname': string | null;
      'subscription:company:user:id': number;
      'subscription:company:user:lastname': string;
      'subscription:company:user:password': string;
      'subscription:company:user:role': 'admin' | 'editor' | 'user';
      'subscription:company:user:status': 'deleted' | 'disabled' | 'enabled';
      'subscription:company:user:updated_at': string;
      'subscription:customer:company:created_at': string;
      'subscription:customer:company:id': number;
      'subscription:customer:company:industry': string | null;
      'subscription:customer:company:MRR': number | null;
      'subscription:customer:company:name': string;
      'subscription:customer:company:nbUsers': number | null;
      'subscription:customer:company:planId': number | null;
      'subscription:customer:company:planPrice': number | null;
      'subscription:customer:company:size': number | null;
      'subscription:customer:company:updated_at': string;
      'subscription:customer:company:user_id': number | null;
      'company:user:company:currentPlan:created_at': string;
      'company:user:company:currentPlan:description': string | null;
      'company:user:company:currentPlan:id': number;
      'company:user:company:currentPlan:interval': 'custom' | 'monthly' | 'yearly';
      'company:user:company:currentPlan:name': string;
      'company:user:company:currentPlan:price': number;
      'company:user:company:currentPlan:updated_at': string;
      'company:user:company:user:avatar': string | null;
      'company:user:company:user:company_id': number | null;
      'company:user:company:user:completed_at': string | null;
      'company:user:company:user:created_at': string;
      'company:user:company:user:email': string;
      'company:user:company:user:firstname': string;
      'company:user:company:user:Fullname': string | null;
      'company:user:company:user:id': number;
      'company:user:company:user:lastname': string;
      'company:user:company:user:password': string;
      'company:user:company:user:role': 'admin' | 'editor' | 'user';
      'company:user:company:user:status': 'deleted' | 'disabled' | 'enabled';
      'company:user:company:user:updated_at': string;
      'customer:company:user:company:created_at': string;
      'customer:company:user:company:id': number;
      'customer:company:user:company:industry': string | null;
      'customer:company:user:company:MRR': number | null;
      'customer:company:user:company:name': string;
      'customer:company:user:company:nbUsers': number | null;
      'customer:company:user:company:planId': number | null;
      'customer:company:user:company:planPrice': number | null;
      'customer:company:user:company:size': number | null;
      'customer:company:user:company:updated_at': string;
      'customer:company:user:company:user_id': number | null;
      'subscription:company:user:company:created_at': string;
      'subscription:company:user:company:id': number;
      'subscription:company:user:company:industry': string | null;
      'subscription:company:user:company:MRR': number | null;
      'subscription:company:user:company:name': string;
      'subscription:company:user:company:nbUsers': number | null;
      'subscription:company:user:company:planId': number | null;
      'subscription:company:user:company:planPrice': number | null;
      'subscription:company:user:company:size': number | null;
      'subscription:company:user:company:updated_at': string;
      'subscription:company:user:company:user_id': number | null;
      'subscription:customer:company:currentPlan:created_at': string;
      'subscription:customer:company:currentPlan:description': string | null;
      'subscription:customer:company:currentPlan:id': number;
      'subscription:customer:company:currentPlan:interval': 'custom' | 'monthly' | 'yearly';
      'subscription:customer:company:currentPlan:name': string;
      'subscription:customer:company:currentPlan:price': number;
      'subscription:customer:company:currentPlan:updated_at': string;
      'subscription:customer:company:user:avatar': string | null;
      'subscription:customer:company:user:company_id': number | null;
      'subscription:customer:company:user:completed_at': string | null;
      'subscription:customer:company:user:created_at': string;
      'subscription:customer:company:user:email': string;
      'subscription:customer:company:user:firstname': string;
      'subscription:customer:company:user:Fullname': string | null;
      'subscription:customer:company:user:id': number;
      'subscription:customer:company:user:lastname': string;
      'subscription:customer:company:user:password': string;
      'subscription:customer:company:user:role': 'admin' | 'editor' | 'user';
      'subscription:customer:company:user:status': 'deleted' | 'disabled' | 'enabled';
      'subscription:customer:company:user:updated_at': string;
      'company:user:company:user:company:created_at': string;
      'company:user:company:user:company:id': number;
      'company:user:company:user:company:industry': string | null;
      'company:user:company:user:company:MRR': number | null;
      'company:user:company:user:company:name': string;
      'company:user:company:user:company:nbUsers': number | null;
      'company:user:company:user:company:planId': number | null;
      'company:user:company:user:company:planPrice': number | null;
      'company:user:company:user:company:size': number | null;
      'company:user:company:user:company:updated_at': string;
      'company:user:company:user:company:user_id': number | null;
      'customer:company:user:company:currentPlan:created_at': string;
      'customer:company:user:company:currentPlan:description': string | null;
      'customer:company:user:company:currentPlan:id': number;
      'customer:company:user:company:currentPlan:interval': 'custom' | 'monthly' | 'yearly';
      'customer:company:user:company:currentPlan:name': string;
      'customer:company:user:company:currentPlan:price': number;
      'customer:company:user:company:currentPlan:updated_at': string;
      'customer:company:user:company:user:avatar': string | null;
      'customer:company:user:company:user:company_id': number | null;
      'customer:company:user:company:user:completed_at': string | null;
      'customer:company:user:company:user:created_at': string;
      'customer:company:user:company:user:email': string;
      'customer:company:user:company:user:firstname': string;
      'customer:company:user:company:user:Fullname': string | null;
      'customer:company:user:company:user:id': number;
      'customer:company:user:company:user:lastname': string;
      'customer:company:user:company:user:password': string;
      'customer:company:user:company:user:role': 'admin' | 'editor' | 'user';
      'customer:company:user:company:user:status': 'deleted' | 'disabled' | 'enabled';
      'customer:company:user:company:user:updated_at': string;
      'subscription:company:user:company:currentPlan:created_at': string;
      'subscription:company:user:company:currentPlan:description': string | null;
      'subscription:company:user:company:currentPlan:id': number;
      'subscription:company:user:company:currentPlan:interval': 'custom' | 'monthly' | 'yearly';
      'subscription:company:user:company:currentPlan:name': string;
      'subscription:company:user:company:currentPlan:price': number;
      'subscription:company:user:company:currentPlan:updated_at': string;
      'subscription:company:user:company:user:avatar': string | null;
      'subscription:company:user:company:user:company_id': number | null;
      'subscription:company:user:company:user:completed_at': string | null;
      'subscription:company:user:company:user:created_at': string;
      'subscription:company:user:company:user:email': string;
      'subscription:company:user:company:user:firstname': string;
      'subscription:company:user:company:user:Fullname': string | null;
      'subscription:company:user:company:user:id': number;
      'subscription:company:user:company:user:lastname': string;
      'subscription:company:user:company:user:password': string;
      'subscription:company:user:company:user:role': 'admin' | 'editor' | 'user';
      'subscription:company:user:company:user:status': 'deleted' | 'disabled' | 'enabled';
      'subscription:company:user:company:user:updated_at': string;
      'subscription:customer:company:user:company:created_at': string;
      'subscription:customer:company:user:company:id': number;
      'subscription:customer:company:user:company:industry': string | null;
      'subscription:customer:company:user:company:MRR': number | null;
      'subscription:customer:company:user:company:name': string;
      'subscription:customer:company:user:company:nbUsers': number | null;
      'subscription:customer:company:user:company:planId': number | null;
      'subscription:customer:company:user:company:planPrice': number | null;
      'subscription:customer:company:user:company:size': number | null;
      'subscription:customer:company:user:company:updated_at': string;
      'subscription:customer:company:user:company:user_id': number | null;
    };
  };
  'plans': {
    plain: {
      'created_at': string;
      'description': string | null;
      'id': number;
      'interval': 'custom' | 'monthly' | 'yearly';
      'name': string;
      'price': number;
      'updated_at': string;
    };
    nested: {};
    flat: {};
  };
  'subscriptions': {
    plain: {
      'commitment': 'monthly' | 'yearly';
      'company_id': number;
      'created_at': string;
      'customer_id': number;
      'discount': number | null;
      'ended_at': string | null;
      'id': number;
      'plan_id': number;
      'renewal_date': string | null;
      'started_at': string;
      'status': 'active' | 'canceled' | 'paused';
      'updated_at': string;
    };
    nested: {
      'company': Schema['companies']['plain'] & Schema['companies']['nested'];
      'customer': Schema['users']['plain'] & Schema['users']['nested'];
      'plan': Schema['plans']['plain'] & Schema['plans']['nested'];
    };
    flat: {
      'company:created_at': string;
      'company:id': number;
      'company:industry': string | null;
      'company:MRR': number | null;
      'company:name': string;
      'company:nbUsers': number | null;
      'company:planId': number | null;
      'company:planPrice': number | null;
      'company:size': number | null;
      'company:updated_at': string;
      'company:user_id': number | null;
      'customer:avatar': string | null;
      'customer:company_id': number | null;
      'customer:completed_at': string | null;
      'customer:created_at': string;
      'customer:email': string;
      'customer:firstname': string;
      'customer:Fullname': string | null;
      'customer:id': number;
      'customer:lastname': string;
      'customer:password': string;
      'customer:role': 'admin' | 'editor' | 'user';
      'customer:status': 'deleted' | 'disabled' | 'enabled';
      'customer:updated_at': string;
      'plan:created_at': string;
      'plan:description': string | null;
      'plan:id': number;
      'plan:interval': 'custom' | 'monthly' | 'yearly';
      'plan:name': string;
      'plan:price': number;
      'plan:updated_at': string;
      'company:currentPlan:created_at': string;
      'company:currentPlan:description': string | null;
      'company:currentPlan:id': number;
      'company:currentPlan:interval': 'custom' | 'monthly' | 'yearly';
      'company:currentPlan:name': string;
      'company:currentPlan:price': number;
      'company:currentPlan:updated_at': string;
      'company:user:avatar': string | null;
      'company:user:company_id': number | null;
      'company:user:completed_at': string | null;
      'company:user:created_at': string;
      'company:user:email': string;
      'company:user:firstname': string;
      'company:user:Fullname': string | null;
      'company:user:id': number;
      'company:user:lastname': string;
      'company:user:password': string;
      'company:user:role': 'admin' | 'editor' | 'user';
      'company:user:status': 'deleted' | 'disabled' | 'enabled';
      'company:user:updated_at': string;
      'customer:company:created_at': string;
      'customer:company:id': number;
      'customer:company:industry': string | null;
      'customer:company:MRR': number | null;
      'customer:company:name': string;
      'customer:company:nbUsers': number | null;
      'customer:company:planId': number | null;
      'customer:company:planPrice': number | null;
      'customer:company:size': number | null;
      'customer:company:updated_at': string;
      'customer:company:user_id': number | null;
      'company:user:company:created_at': string;
      'company:user:company:id': number;
      'company:user:company:industry': string | null;
      'company:user:company:MRR': number | null;
      'company:user:company:name': string;
      'company:user:company:nbUsers': number | null;
      'company:user:company:planId': number | null;
      'company:user:company:planPrice': number | null;
      'company:user:company:size': number | null;
      'company:user:company:updated_at': string;
      'company:user:company:user_id': number | null;
      'customer:company:currentPlan:created_at': string;
      'customer:company:currentPlan:description': string | null;
      'customer:company:currentPlan:id': number;
      'customer:company:currentPlan:interval': 'custom' | 'monthly' | 'yearly';
      'customer:company:currentPlan:name': string;
      'customer:company:currentPlan:price': number;
      'customer:company:currentPlan:updated_at': string;
      'customer:company:user:avatar': string | null;
      'customer:company:user:company_id': number | null;
      'customer:company:user:completed_at': string | null;
      'customer:company:user:created_at': string;
      'customer:company:user:email': string;
      'customer:company:user:firstname': string;
      'customer:company:user:Fullname': string | null;
      'customer:company:user:id': number;
      'customer:company:user:lastname': string;
      'customer:company:user:password': string;
      'customer:company:user:role': 'admin' | 'editor' | 'user';
      'customer:company:user:status': 'deleted' | 'disabled' | 'enabled';
      'customer:company:user:updated_at': string;
      'company:user:company:currentPlan:created_at': string;
      'company:user:company:currentPlan:description': string | null;
      'company:user:company:currentPlan:id': number;
      'company:user:company:currentPlan:interval': 'custom' | 'monthly' | 'yearly';
      'company:user:company:currentPlan:name': string;
      'company:user:company:currentPlan:price': number;
      'company:user:company:currentPlan:updated_at': string;
      'company:user:company:user:avatar': string | null;
      'company:user:company:user:company_id': number | null;
      'company:user:company:user:completed_at': string | null;
      'company:user:company:user:created_at': string;
      'company:user:company:user:email': string;
      'company:user:company:user:firstname': string;
      'company:user:company:user:Fullname': string | null;
      'company:user:company:user:id': number;
      'company:user:company:user:lastname': string;
      'company:user:company:user:password': string;
      'company:user:company:user:role': 'admin' | 'editor' | 'user';
      'company:user:company:user:status': 'deleted' | 'disabled' | 'enabled';
      'company:user:company:user:updated_at': string;
      'customer:company:user:company:created_at': string;
      'customer:company:user:company:id': number;
      'customer:company:user:company:industry': string | null;
      'customer:company:user:company:MRR': number | null;
      'customer:company:user:company:name': string;
      'customer:company:user:company:nbUsers': number | null;
      'customer:company:user:company:planId': number | null;
      'customer:company:user:company:planPrice': number | null;
      'customer:company:user:company:size': number | null;
      'customer:company:user:company:updated_at': string;
      'customer:company:user:company:user_id': number | null;
      'company:user:company:user:company:created_at': string;
      'company:user:company:user:company:id': number;
      'company:user:company:user:company:industry': string | null;
      'company:user:company:user:company:MRR': number | null;
      'company:user:company:user:company:name': string;
      'company:user:company:user:company:nbUsers': number | null;
      'company:user:company:user:company:planId': number | null;
      'company:user:company:user:company:planPrice': number | null;
      'company:user:company:user:company:size': number | null;
      'company:user:company:user:company:updated_at': string;
      'company:user:company:user:company:user_id': number | null;
      'customer:company:user:company:currentPlan:created_at': string;
      'customer:company:user:company:currentPlan:description': string | null;
      'customer:company:user:company:currentPlan:id': number;
      'customer:company:user:company:currentPlan:interval': 'custom' | 'monthly' | 'yearly';
      'customer:company:user:company:currentPlan:name': string;
      'customer:company:user:company:currentPlan:price': number;
      'customer:company:user:company:currentPlan:updated_at': string;
      'customer:company:user:company:user:avatar': string | null;
      'customer:company:user:company:user:company_id': number | null;
      'customer:company:user:company:user:completed_at': string | null;
      'customer:company:user:company:user:created_at': string;
      'customer:company:user:company:user:email': string;
      'customer:company:user:company:user:firstname': string;
      'customer:company:user:company:user:Fullname': string | null;
      'customer:company:user:company:user:id': number;
      'customer:company:user:company:user:lastname': string;
      'customer:company:user:company:user:password': string;
      'customer:company:user:company:user:role': 'admin' | 'editor' | 'user';
      'customer:company:user:company:user:status': 'deleted' | 'disabled' | 'enabled';
      'customer:company:user:company:user:updated_at': string;
    };
  };
  'support_tickets': {
    plain: {
      'closed_at': string | null;
      'company_id': number;
      'created_at': string;
      'customer_id': number;
      'id': number;
      'issue_topic': string;
      'status': 'assigned' | 'closed' | 'new';
      'updated_at': string;
    };
    nested: {
      'company': Schema['companies']['plain'] & Schema['companies']['nested'];
      'customer': Schema['users']['plain'] & Schema['users']['nested'];
    };
    flat: {
      'company:created_at': string;
      'company:id': number;
      'company:industry': string | null;
      'company:MRR': number | null;
      'company:name': string;
      'company:nbUsers': number | null;
      'company:planId': number | null;
      'company:planPrice': number | null;
      'company:size': number | null;
      'company:updated_at': string;
      'company:user_id': number | null;
      'customer:avatar': string | null;
      'customer:company_id': number | null;
      'customer:completed_at': string | null;
      'customer:created_at': string;
      'customer:email': string;
      'customer:firstname': string;
      'customer:Fullname': string | null;
      'customer:id': number;
      'customer:lastname': string;
      'customer:password': string;
      'customer:role': 'admin' | 'editor' | 'user';
      'customer:status': 'deleted' | 'disabled' | 'enabled';
      'customer:updated_at': string;
      'company:currentPlan:created_at': string;
      'company:currentPlan:description': string | null;
      'company:currentPlan:id': number;
      'company:currentPlan:interval': 'custom' | 'monthly' | 'yearly';
      'company:currentPlan:name': string;
      'company:currentPlan:price': number;
      'company:currentPlan:updated_at': string;
      'company:user:avatar': string | null;
      'company:user:company_id': number | null;
      'company:user:completed_at': string | null;
      'company:user:created_at': string;
      'company:user:email': string;
      'company:user:firstname': string;
      'company:user:Fullname': string | null;
      'company:user:id': number;
      'company:user:lastname': string;
      'company:user:password': string;
      'company:user:role': 'admin' | 'editor' | 'user';
      'company:user:status': 'deleted' | 'disabled' | 'enabled';
      'company:user:updated_at': string;
      'customer:company:created_at': string;
      'customer:company:id': number;
      'customer:company:industry': string | null;
      'customer:company:MRR': number | null;
      'customer:company:name': string;
      'customer:company:nbUsers': number | null;
      'customer:company:planId': number | null;
      'customer:company:planPrice': number | null;
      'customer:company:size': number | null;
      'customer:company:updated_at': string;
      'customer:company:user_id': number | null;
      'company:user:company:created_at': string;
      'company:user:company:id': number;
      'company:user:company:industry': string | null;
      'company:user:company:MRR': number | null;
      'company:user:company:name': string;
      'company:user:company:nbUsers': number | null;
      'company:user:company:planId': number | null;
      'company:user:company:planPrice': number | null;
      'company:user:company:size': number | null;
      'company:user:company:updated_at': string;
      'company:user:company:user_id': number | null;
      'customer:company:currentPlan:created_at': string;
      'customer:company:currentPlan:description': string | null;
      'customer:company:currentPlan:id': number;
      'customer:company:currentPlan:interval': 'custom' | 'monthly' | 'yearly';
      'customer:company:currentPlan:name': string;
      'customer:company:currentPlan:price': number;
      'customer:company:currentPlan:updated_at': string;
      'customer:company:user:avatar': string | null;
      'customer:company:user:company_id': number | null;
      'customer:company:user:completed_at': string | null;
      'customer:company:user:created_at': string;
      'customer:company:user:email': string;
      'customer:company:user:firstname': string;
      'customer:company:user:Fullname': string | null;
      'customer:company:user:id': number;
      'customer:company:user:lastname': string;
      'customer:company:user:password': string;
      'customer:company:user:role': 'admin' | 'editor' | 'user';
      'customer:company:user:status': 'deleted' | 'disabled' | 'enabled';
      'customer:company:user:updated_at': string;
      'company:user:company:currentPlan:created_at': string;
      'company:user:company:currentPlan:description': string | null;
      'company:user:company:currentPlan:id': number;
      'company:user:company:currentPlan:interval': 'custom' | 'monthly' | 'yearly';
      'company:user:company:currentPlan:name': string;
      'company:user:company:currentPlan:price': number;
      'company:user:company:currentPlan:updated_at': string;
      'company:user:company:user:avatar': string | null;
      'company:user:company:user:company_id': number | null;
      'company:user:company:user:completed_at': string | null;
      'company:user:company:user:created_at': string;
      'company:user:company:user:email': string;
      'company:user:company:user:firstname': string;
      'company:user:company:user:Fullname': string | null;
      'company:user:company:user:id': number;
      'company:user:company:user:lastname': string;
      'company:user:company:user:password': string;
      'company:user:company:user:role': 'admin' | 'editor' | 'user';
      'company:user:company:user:status': 'deleted' | 'disabled' | 'enabled';
      'company:user:company:user:updated_at': string;
      'customer:company:user:company:created_at': string;
      'customer:company:user:company:id': number;
      'customer:company:user:company:industry': string | null;
      'customer:company:user:company:MRR': number | null;
      'customer:company:user:company:name': string;
      'customer:company:user:company:nbUsers': number | null;
      'customer:company:user:company:planId': number | null;
      'customer:company:user:company:planPrice': number | null;
      'customer:company:user:company:size': number | null;
      'customer:company:user:company:updated_at': string;
      'customer:company:user:company:user_id': number | null;
      'company:user:company:user:company:created_at': string;
      'company:user:company:user:company:id': number;
      'company:user:company:user:company:industry': string | null;
      'company:user:company:user:company:MRR': number | null;
      'company:user:company:user:company:name': string;
      'company:user:company:user:company:nbUsers': number | null;
      'company:user:company:user:company:planId': number | null;
      'company:user:company:user:company:planPrice': number | null;
      'company:user:company:user:company:size': number | null;
      'company:user:company:user:company:updated_at': string;
      'company:user:company:user:company:user_id': number | null;
      'customer:company:user:company:currentPlan:created_at': string;
      'customer:company:user:company:currentPlan:description': string | null;
      'customer:company:user:company:currentPlan:id': number;
      'customer:company:user:company:currentPlan:interval': 'custom' | 'monthly' | 'yearly';
      'customer:company:user:company:currentPlan:name': string;
      'customer:company:user:company:currentPlan:price': number;
      'customer:company:user:company:currentPlan:updated_at': string;
      'customer:company:user:company:user:avatar': string | null;
      'customer:company:user:company:user:company_id': number | null;
      'customer:company:user:company:user:completed_at': string | null;
      'customer:company:user:company:user:created_at': string;
      'customer:company:user:company:user:email': string;
      'customer:company:user:company:user:firstname': string;
      'customer:company:user:company:user:Fullname': string | null;
      'customer:company:user:company:user:id': number;
      'customer:company:user:company:user:lastname': string;
      'customer:company:user:company:user:password': string;
      'customer:company:user:company:user:role': 'admin' | 'editor' | 'user';
      'customer:company:user:company:user:status': 'deleted' | 'disabled' | 'enabled';
      'customer:company:user:company:user:updated_at': string;
    };
  };
  'transactions': {
    plain: {
      'amount': number;
      'company_id': number;
      'customer_id': number;
      'executed_at': string;
      'id': number;
      'invoice_id': number;
      'payment_method': 'bank_transfer' | 'credit_card' | 'paypal' | 'stripe';
    };
    nested: {
      'company': Schema['companies']['plain'] & Schema['companies']['nested'];
      'customer': Schema['users']['plain'] & Schema['users']['nested'];
      'invoice': Schema['invoices']['plain'] & Schema['invoices']['nested'];
    };
    flat: {
      'company:created_at': string;
      'company:id': number;
      'company:industry': string | null;
      'company:MRR': number | null;
      'company:name': string;
      'company:nbUsers': number | null;
      'company:planId': number | null;
      'company:planPrice': number | null;
      'company:size': number | null;
      'company:updated_at': string;
      'company:user_id': number | null;
      'customer:avatar': string | null;
      'customer:company_id': number | null;
      'customer:completed_at': string | null;
      'customer:created_at': string;
      'customer:email': string;
      'customer:firstname': string;
      'customer:Fullname': string | null;
      'customer:id': number;
      'customer:lastname': string;
      'customer:password': string;
      'customer:role': 'admin' | 'editor' | 'user';
      'customer:status': 'deleted' | 'disabled' | 'enabled';
      'customer:updated_at': string;
      'invoice:amount': number;
      'invoice:company_id': number;
      'invoice:created_at': string;
      'invoice:customer_id': number;
      'invoice:id': number;
      'invoice:plan_id': number;
      'invoice:status': 'paid' | 'pending' | 'void';
      'invoice:subscription_id': number;
      'invoice:updated_at': string;
      'company:currentPlan:created_at': string;
      'company:currentPlan:description': string | null;
      'company:currentPlan:id': number;
      'company:currentPlan:interval': 'custom' | 'monthly' | 'yearly';
      'company:currentPlan:name': string;
      'company:currentPlan:price': number;
      'company:currentPlan:updated_at': string;
      'company:user:avatar': string | null;
      'company:user:company_id': number | null;
      'company:user:completed_at': string | null;
      'company:user:created_at': string;
      'company:user:email': string;
      'company:user:firstname': string;
      'company:user:Fullname': string | null;
      'company:user:id': number;
      'company:user:lastname': string;
      'company:user:password': string;
      'company:user:role': 'admin' | 'editor' | 'user';
      'company:user:status': 'deleted' | 'disabled' | 'enabled';
      'company:user:updated_at': string;
      'customer:company:created_at': string;
      'customer:company:id': number;
      'customer:company:industry': string | null;
      'customer:company:MRR': number | null;
      'customer:company:name': string;
      'customer:company:nbUsers': number | null;
      'customer:company:planId': number | null;
      'customer:company:planPrice': number | null;
      'customer:company:size': number | null;
      'customer:company:updated_at': string;
      'customer:company:user_id': number | null;
      'invoice:company:created_at': string;
      'invoice:company:id': number;
      'invoice:company:industry': string | null;
      'invoice:company:MRR': number | null;
      'invoice:company:name': string;
      'invoice:company:nbUsers': number | null;
      'invoice:company:planId': number | null;
      'invoice:company:planPrice': number | null;
      'invoice:company:size': number | null;
      'invoice:company:updated_at': string;
      'invoice:company:user_id': number | null;
      'invoice:customer:avatar': string | null;
      'invoice:customer:company_id': number | null;
      'invoice:customer:completed_at': string | null;
      'invoice:customer:created_at': string;
      'invoice:customer:email': string;
      'invoice:customer:firstname': string;
      'invoice:customer:Fullname': string | null;
      'invoice:customer:id': number;
      'invoice:customer:lastname': string;
      'invoice:customer:password': string;
      'invoice:customer:role': 'admin' | 'editor' | 'user';
      'invoice:customer:status': 'deleted' | 'disabled' | 'enabled';
      'invoice:customer:updated_at': string;
      'invoice:plan:created_at': string;
      'invoice:plan:description': string | null;
      'invoice:plan:id': number;
      'invoice:plan:interval': 'custom' | 'monthly' | 'yearly';
      'invoice:plan:name': string;
      'invoice:plan:price': number;
      'invoice:plan:updated_at': string;
      'invoice:subscription:commitment': 'monthly' | 'yearly';
      'invoice:subscription:company_id': number;
      'invoice:subscription:created_at': string;
      'invoice:subscription:customer_id': number;
      'invoice:subscription:discount': number | null;
      'invoice:subscription:ended_at': string | null;
      'invoice:subscription:id': number;
      'invoice:subscription:plan_id': number;
      'invoice:subscription:renewal_date': string | null;
      'invoice:subscription:started_at': string;
      'invoice:subscription:status': 'active' | 'canceled' | 'paused';
      'invoice:subscription:updated_at': string;
      'company:user:company:created_at': string;
      'company:user:company:id': number;
      'company:user:company:industry': string | null;
      'company:user:company:MRR': number | null;
      'company:user:company:name': string;
      'company:user:company:nbUsers': number | null;
      'company:user:company:planId': number | null;
      'company:user:company:planPrice': number | null;
      'company:user:company:size': number | null;
      'company:user:company:updated_at': string;
      'company:user:company:user_id': number | null;
      'customer:company:currentPlan:created_at': string;
      'customer:company:currentPlan:description': string | null;
      'customer:company:currentPlan:id': number;
      'customer:company:currentPlan:interval': 'custom' | 'monthly' | 'yearly';
      'customer:company:currentPlan:name': string;
      'customer:company:currentPlan:price': number;
      'customer:company:currentPlan:updated_at': string;
      'customer:company:user:avatar': string | null;
      'customer:company:user:company_id': number | null;
      'customer:company:user:completed_at': string | null;
      'customer:company:user:created_at': string;
      'customer:company:user:email': string;
      'customer:company:user:firstname': string;
      'customer:company:user:Fullname': string | null;
      'customer:company:user:id': number;
      'customer:company:user:lastname': string;
      'customer:company:user:password': string;
      'customer:company:user:role': 'admin' | 'editor' | 'user';
      'customer:company:user:status': 'deleted' | 'disabled' | 'enabled';
      'customer:company:user:updated_at': string;
      'invoice:company:currentPlan:created_at': string;
      'invoice:company:currentPlan:description': string | null;
      'invoice:company:currentPlan:id': number;
      'invoice:company:currentPlan:interval': 'custom' | 'monthly' | 'yearly';
      'invoice:company:currentPlan:name': string;
      'invoice:company:currentPlan:price': number;
      'invoice:company:currentPlan:updated_at': string;
      'invoice:company:user:avatar': string | null;
      'invoice:company:user:company_id': number | null;
      'invoice:company:user:completed_at': string | null;
      'invoice:company:user:created_at': string;
      'invoice:company:user:email': string;
      'invoice:company:user:firstname': string;
      'invoice:company:user:Fullname': string | null;
      'invoice:company:user:id': number;
      'invoice:company:user:lastname': string;
      'invoice:company:user:password': string;
      'invoice:company:user:role': 'admin' | 'editor' | 'user';
      'invoice:company:user:status': 'deleted' | 'disabled' | 'enabled';
      'invoice:company:user:updated_at': string;
      'invoice:customer:company:created_at': string;
      'invoice:customer:company:id': number;
      'invoice:customer:company:industry': string | null;
      'invoice:customer:company:MRR': number | null;
      'invoice:customer:company:name': string;
      'invoice:customer:company:nbUsers': number | null;
      'invoice:customer:company:planId': number | null;
      'invoice:customer:company:planPrice': number | null;
      'invoice:customer:company:size': number | null;
      'invoice:customer:company:updated_at': string;
      'invoice:customer:company:user_id': number | null;
      'invoice:subscription:company:created_at': string;
      'invoice:subscription:company:id': number;
      'invoice:subscription:company:industry': string | null;
      'invoice:subscription:company:MRR': number | null;
      'invoice:subscription:company:name': string;
      'invoice:subscription:company:nbUsers': number | null;
      'invoice:subscription:company:planId': number | null;
      'invoice:subscription:company:planPrice': number | null;
      'invoice:subscription:company:size': number | null;
      'invoice:subscription:company:updated_at': string;
      'invoice:subscription:company:user_id': number | null;
      'invoice:subscription:customer:avatar': string | null;
      'invoice:subscription:customer:company_id': number | null;
      'invoice:subscription:customer:completed_at': string | null;
      'invoice:subscription:customer:created_at': string;
      'invoice:subscription:customer:email': string;
      'invoice:subscription:customer:firstname': string;
      'invoice:subscription:customer:Fullname': string | null;
      'invoice:subscription:customer:id': number;
      'invoice:subscription:customer:lastname': string;
      'invoice:subscription:customer:password': string;
      'invoice:subscription:customer:role': 'admin' | 'editor' | 'user';
      'invoice:subscription:customer:status': 'deleted' | 'disabled' | 'enabled';
      'invoice:subscription:customer:updated_at': string;
      'invoice:subscription:plan:created_at': string;
      'invoice:subscription:plan:description': string | null;
      'invoice:subscription:plan:id': number;
      'invoice:subscription:plan:interval': 'custom' | 'monthly' | 'yearly';
      'invoice:subscription:plan:name': string;
      'invoice:subscription:plan:price': number;
      'invoice:subscription:plan:updated_at': string;
      'company:user:company:currentPlan:created_at': string;
      'company:user:company:currentPlan:description': string | null;
      'company:user:company:currentPlan:id': number;
      'company:user:company:currentPlan:interval': 'custom' | 'monthly' | 'yearly';
      'company:user:company:currentPlan:name': string;
      'company:user:company:currentPlan:price': number;
      'company:user:company:currentPlan:updated_at': string;
      'company:user:company:user:avatar': string | null;
      'company:user:company:user:company_id': number | null;
      'company:user:company:user:completed_at': string | null;
      'company:user:company:user:created_at': string;
      'company:user:company:user:email': string;
      'company:user:company:user:firstname': string;
      'company:user:company:user:Fullname': string | null;
      'company:user:company:user:id': number;
      'company:user:company:user:lastname': string;
      'company:user:company:user:password': string;
      'company:user:company:user:role': 'admin' | 'editor' | 'user';
      'company:user:company:user:status': 'deleted' | 'disabled' | 'enabled';
      'company:user:company:user:updated_at': string;
      'customer:company:user:company:created_at': string;
      'customer:company:user:company:id': number;
      'customer:company:user:company:industry': string | null;
      'customer:company:user:company:MRR': number | null;
      'customer:company:user:company:name': string;
      'customer:company:user:company:nbUsers': number | null;
      'customer:company:user:company:planId': number | null;
      'customer:company:user:company:planPrice': number | null;
      'customer:company:user:company:size': number | null;
      'customer:company:user:company:updated_at': string;
      'customer:company:user:company:user_id': number | null;
      'invoice:company:user:company:created_at': string;
      'invoice:company:user:company:id': number;
      'invoice:company:user:company:industry': string | null;
      'invoice:company:user:company:MRR': number | null;
      'invoice:company:user:company:name': string;
      'invoice:company:user:company:nbUsers': number | null;
      'invoice:company:user:company:planId': number | null;
      'invoice:company:user:company:planPrice': number | null;
      'invoice:company:user:company:size': number | null;
      'invoice:company:user:company:updated_at': string;
      'invoice:company:user:company:user_id': number | null;
      'invoice:customer:company:currentPlan:created_at': string;
      'invoice:customer:company:currentPlan:description': string | null;
      'invoice:customer:company:currentPlan:id': number;
      'invoice:customer:company:currentPlan:interval': 'custom' | 'monthly' | 'yearly';
      'invoice:customer:company:currentPlan:name': string;
      'invoice:customer:company:currentPlan:price': number;
      'invoice:customer:company:currentPlan:updated_at': string;
      'invoice:customer:company:user:avatar': string | null;
      'invoice:customer:company:user:company_id': number | null;
      'invoice:customer:company:user:completed_at': string | null;
      'invoice:customer:company:user:created_at': string;
      'invoice:customer:company:user:email': string;
      'invoice:customer:company:user:firstname': string;
      'invoice:customer:company:user:Fullname': string | null;
      'invoice:customer:company:user:id': number;
      'invoice:customer:company:user:lastname': string;
      'invoice:customer:company:user:password': string;
      'invoice:customer:company:user:role': 'admin' | 'editor' | 'user';
      'invoice:customer:company:user:status': 'deleted' | 'disabled' | 'enabled';
      'invoice:customer:company:user:updated_at': string;
      'invoice:subscription:company:currentPlan:created_at': string;
      'invoice:subscription:company:currentPlan:description': string | null;
      'invoice:subscription:company:currentPlan:id': number;
      'invoice:subscription:company:currentPlan:interval': 'custom' | 'monthly' | 'yearly';
      'invoice:subscription:company:currentPlan:name': string;
      'invoice:subscription:company:currentPlan:price': number;
      'invoice:subscription:company:currentPlan:updated_at': string;
      'invoice:subscription:company:user:avatar': string | null;
      'invoice:subscription:company:user:company_id': number | null;
      'invoice:subscription:company:user:completed_at': string | null;
      'invoice:subscription:company:user:created_at': string;
      'invoice:subscription:company:user:email': string;
      'invoice:subscription:company:user:firstname': string;
      'invoice:subscription:company:user:Fullname': string | null;
      'invoice:subscription:company:user:id': number;
      'invoice:subscription:company:user:lastname': string;
      'invoice:subscription:company:user:password': string;
      'invoice:subscription:company:user:role': 'admin' | 'editor' | 'user';
      'invoice:subscription:company:user:status': 'deleted' | 'disabled' | 'enabled';
      'invoice:subscription:company:user:updated_at': string;
      'invoice:subscription:customer:company:created_at': string;
      'invoice:subscription:customer:company:id': number;
      'invoice:subscription:customer:company:industry': string | null;
      'invoice:subscription:customer:company:MRR': number | null;
      'invoice:subscription:customer:company:name': string;
      'invoice:subscription:customer:company:nbUsers': number | null;
      'invoice:subscription:customer:company:planId': number | null;
      'invoice:subscription:customer:company:planPrice': number | null;
      'invoice:subscription:customer:company:size': number | null;
      'invoice:subscription:customer:company:updated_at': string;
      'invoice:subscription:customer:company:user_id': number | null;
      'company:user:company:user:company:created_at': string;
      'company:user:company:user:company:id': number;
      'company:user:company:user:company:industry': string | null;
      'company:user:company:user:company:MRR': number | null;
      'company:user:company:user:company:name': string;
      'company:user:company:user:company:nbUsers': number | null;
      'company:user:company:user:company:planId': number | null;
      'company:user:company:user:company:planPrice': number | null;
      'company:user:company:user:company:size': number | null;
      'company:user:company:user:company:updated_at': string;
      'company:user:company:user:company:user_id': number | null;
      'customer:company:user:company:currentPlan:created_at': string;
      'customer:company:user:company:currentPlan:description': string | null;
      'customer:company:user:company:currentPlan:id': number;
      'customer:company:user:company:currentPlan:interval': 'custom' | 'monthly' | 'yearly';
      'customer:company:user:company:currentPlan:name': string;
      'customer:company:user:company:currentPlan:price': number;
      'customer:company:user:company:currentPlan:updated_at': string;
      'customer:company:user:company:user:avatar': string | null;
      'customer:company:user:company:user:company_id': number | null;
      'customer:company:user:company:user:completed_at': string | null;
      'customer:company:user:company:user:created_at': string;
      'customer:company:user:company:user:email': string;
      'customer:company:user:company:user:firstname': string;
      'customer:company:user:company:user:Fullname': string | null;
      'customer:company:user:company:user:id': number;
      'customer:company:user:company:user:lastname': string;
      'customer:company:user:company:user:password': string;
      'customer:company:user:company:user:role': 'admin' | 'editor' | 'user';
      'customer:company:user:company:user:status': 'deleted' | 'disabled' | 'enabled';
      'customer:company:user:company:user:updated_at': string;
      'invoice:company:user:company:currentPlan:created_at': string;
      'invoice:company:user:company:currentPlan:description': string | null;
      'invoice:company:user:company:currentPlan:id': number;
      'invoice:company:user:company:currentPlan:interval': 'custom' | 'monthly' | 'yearly';
      'invoice:company:user:company:currentPlan:name': string;
      'invoice:company:user:company:currentPlan:price': number;
      'invoice:company:user:company:currentPlan:updated_at': string;
      'invoice:company:user:company:user:avatar': string | null;
      'invoice:company:user:company:user:company_id': number | null;
      'invoice:company:user:company:user:completed_at': string | null;
      'invoice:company:user:company:user:created_at': string;
      'invoice:company:user:company:user:email': string;
      'invoice:company:user:company:user:firstname': string;
      'invoice:company:user:company:user:Fullname': string | null;
      'invoice:company:user:company:user:id': number;
      'invoice:company:user:company:user:lastname': string;
      'invoice:company:user:company:user:password': string;
      'invoice:company:user:company:user:role': 'admin' | 'editor' | 'user';
      'invoice:company:user:company:user:status': 'deleted' | 'disabled' | 'enabled';
      'invoice:company:user:company:user:updated_at': string;
      'invoice:customer:company:user:company:created_at': string;
      'invoice:customer:company:user:company:id': number;
      'invoice:customer:company:user:company:industry': string | null;
      'invoice:customer:company:user:company:MRR': number | null;
      'invoice:customer:company:user:company:name': string;
      'invoice:customer:company:user:company:nbUsers': number | null;
      'invoice:customer:company:user:company:planId': number | null;
      'invoice:customer:company:user:company:planPrice': number | null;
      'invoice:customer:company:user:company:size': number | null;
      'invoice:customer:company:user:company:updated_at': string;
      'invoice:customer:company:user:company:user_id': number | null;
      'invoice:subscription:company:user:company:created_at': string;
      'invoice:subscription:company:user:company:id': number;
      'invoice:subscription:company:user:company:industry': string | null;
      'invoice:subscription:company:user:company:MRR': number | null;
      'invoice:subscription:company:user:company:name': string;
      'invoice:subscription:company:user:company:nbUsers': number | null;
      'invoice:subscription:company:user:company:planId': number | null;
      'invoice:subscription:company:user:company:planPrice': number | null;
      'invoice:subscription:company:user:company:size': number | null;
      'invoice:subscription:company:user:company:updated_at': string;
      'invoice:subscription:company:user:company:user_id': number | null;
      'invoice:subscription:customer:company:currentPlan:created_at': string;
      'invoice:subscription:customer:company:currentPlan:description': string | null;
      'invoice:subscription:customer:company:currentPlan:id': number;
      'invoice:subscription:customer:company:currentPlan:interval': 'custom' | 'monthly' | 'yearly';
      'invoice:subscription:customer:company:currentPlan:name': string;
      'invoice:subscription:customer:company:currentPlan:price': number;
      'invoice:subscription:customer:company:currentPlan:updated_at': string;
      'invoice:subscription:customer:company:user:avatar': string | null;
      'invoice:subscription:customer:company:user:company_id': number | null;
      'invoice:subscription:customer:company:user:completed_at': string | null;
      'invoice:subscription:customer:company:user:created_at': string;
      'invoice:subscription:customer:company:user:email': string;
      'invoice:subscription:customer:company:user:firstname': string;
      'invoice:subscription:customer:company:user:Fullname': string | null;
      'invoice:subscription:customer:company:user:id': number;
      'invoice:subscription:customer:company:user:lastname': string;
      'invoice:subscription:customer:company:user:password': string;
      'invoice:subscription:customer:company:user:role': 'admin' | 'editor' | 'user';
      'invoice:subscription:customer:company:user:status': 'deleted' | 'disabled' | 'enabled';
      'invoice:subscription:customer:company:user:updated_at': string;
    };
  };
  'users': {
    plain: {
      'avatar': string | null;
      'company_id': number | null;
      'completed_at': string | null;
      'created_at': string;
      'email': string;
      'firstname': string;
      'Fullname': string | null;
      'id': number;
      'lastname': string;
      'password': string;
      'role': 'admin' | 'editor' | 'user';
      'status': 'deleted' | 'disabled' | 'enabled';
      'updated_at': string;
    };
    nested: {
      'company': Schema['companies']['plain'] & Schema['companies']['nested'];
    };
    flat: {
      'company:created_at': string;
      'company:id': number;
      'company:industry': string | null;
      'company:MRR': number | null;
      'company:name': string;
      'company:nbUsers': number | null;
      'company:planId': number | null;
      'company:planPrice': number | null;
      'company:size': number | null;
      'company:updated_at': string;
      'company:user_id': number | null;
      'company:currentPlan:created_at': string;
      'company:currentPlan:description': string | null;
      'company:currentPlan:id': number;
      'company:currentPlan:interval': 'custom' | 'monthly' | 'yearly';
      'company:currentPlan:name': string;
      'company:currentPlan:price': number;
      'company:currentPlan:updated_at': string;
      'company:user:avatar': string | null;
      'company:user:company_id': number | null;
      'company:user:completed_at': string | null;
      'company:user:created_at': string;
      'company:user:email': string;
      'company:user:firstname': string;
      'company:user:Fullname': string | null;
      'company:user:id': number;
      'company:user:lastname': string;
      'company:user:password': string;
      'company:user:role': 'admin' | 'editor' | 'user';
      'company:user:status': 'deleted' | 'disabled' | 'enabled';
      'company:user:updated_at': string;
      'company:user:company:created_at': string;
      'company:user:company:id': number;
      'company:user:company:industry': string | null;
      'company:user:company:MRR': number | null;
      'company:user:company:name': string;
      'company:user:company:nbUsers': number | null;
      'company:user:company:planId': number | null;
      'company:user:company:planPrice': number | null;
      'company:user:company:size': number | null;
      'company:user:company:updated_at': string;
      'company:user:company:user_id': number | null;
      'company:user:company:currentPlan:created_at': string;
      'company:user:company:currentPlan:description': string | null;
      'company:user:company:currentPlan:id': number;
      'company:user:company:currentPlan:interval': 'custom' | 'monthly' | 'yearly';
      'company:user:company:currentPlan:name': string;
      'company:user:company:currentPlan:price': number;
      'company:user:company:currentPlan:updated_at': string;
      'company:user:company:user:avatar': string | null;
      'company:user:company:user:company_id': number | null;
      'company:user:company:user:completed_at': string | null;
      'company:user:company:user:created_at': string;
      'company:user:company:user:email': string;
      'company:user:company:user:firstname': string;
      'company:user:company:user:Fullname': string | null;
      'company:user:company:user:id': number;
      'company:user:company:user:lastname': string;
      'company:user:company:user:password': string;
      'company:user:company:user:role': 'admin' | 'editor' | 'user';
      'company:user:company:user:status': 'deleted' | 'disabled' | 'enabled';
      'company:user:company:user:updated_at': string;
      'company:user:company:user:company:created_at': string;
      'company:user:company:user:company:id': number;
      'company:user:company:user:company:industry': string | null;
      'company:user:company:user:company:MRR': number | null;
      'company:user:company:user:company:name': string;
      'company:user:company:user:company:nbUsers': number | null;
      'company:user:company:user:company:planId': number | null;
      'company:user:company:user:company:planPrice': number | null;
      'company:user:company:user:company:size': number | null;
      'company:user:company:user:company:updated_at': string;
      'company:user:company:user:company:user_id': number | null;
    };
  };
};
