/* eslint-disable */
export type Schema = {
  'activities': {
    plain: {
      'id': number;
      'customer_id': number;
      'company_id': number;
      'feature_id': number;
      'logged_at': string;
    };
    nested: {
      'customer': Schema['users']['plain'] & Schema['users']['nested'];
      'company': Schema['companies']['plain'] & Schema['companies']['nested'];
      'feature': Schema['features']['plain'] & Schema['features']['nested'];
    };
    flat: {
      'customer:id': number;
      'customer:firstname': string;
      'customer:lastname': string;
      'customer:email': string;
      'customer:password': string;
      'customer:avatar': string;
      'customer:role': 'user' | 'editor' | 'admin';
      'customer:status': 'enabled' | 'disabled' | 'deleted';
      'customer:company_id': number;
      'customer:created_at': string;
      'customer:updated_at': string;
      'customer:completed_at': string;
      'customer:Fullname': string;
      'customer:company:id': number;
      'customer:company:name': string;
      'customer:company:industry': string;
      'customer:company:size': number;
      'customer:company:created_at': string;
      'customer:company:updated_at': string;
      'customer:company:user_id': number;
      'customer:company:planId': number;
      'customer:company:nbUsers': number;
      'customer:company:planPrice': number;
      'customer:company:MRR': number;
      'customer:company:user:id': number;
      'customer:company:user:firstname': string;
      'customer:company:user:lastname': string;
      'customer:company:user:email': string;
      'customer:company:user:password': string;
      'customer:company:user:avatar': string;
      'customer:company:user:role': 'user' | 'editor' | 'admin';
      'customer:company:user:status': 'enabled' | 'disabled' | 'deleted';
      'customer:company:user:company_id': number;
      'customer:company:user:created_at': string;
      'customer:company:user:updated_at': string;
      'customer:company:user:completed_at': string;
      'customer:company:user:Fullname': string;
      'customer:company:user:company:id': number;
      'customer:company:user:company:name': string;
      'customer:company:user:company:industry': string;
      'customer:company:user:company:size': number;
      'customer:company:user:company:created_at': string;
      'customer:company:user:company:updated_at': string;
      'customer:company:user:company:user_id': number;
      'customer:company:user:company:planId': number;
      'customer:company:user:company:nbUsers': number;
      'customer:company:user:company:planPrice': number;
      'customer:company:user:company:MRR': number;
      'customer:company:user:company:user:id': number;
      'customer:company:user:company:user:firstname': string;
      'customer:company:user:company:user:lastname': string;
      'customer:company:user:company:user:email': string;
      'customer:company:user:company:user:password': string;
      'customer:company:user:company:user:avatar': string;
      'customer:company:user:company:user:role': 'user' | 'editor' | 'admin';
      'customer:company:user:company:user:status': 'enabled' | 'disabled' | 'deleted';
      'customer:company:user:company:user:company_id': number;
      'customer:company:user:company:user:created_at': string;
      'customer:company:user:company:user:updated_at': string;
      'customer:company:user:company:user:completed_at': string;
      'customer:company:user:company:user:Fullname': string;
      'customer:company:user:company:currentPlan:id': number;
      'customer:company:user:company:currentPlan:name': string;
      'customer:company:user:company:currentPlan:price': number;
      'customer:company:user:company:currentPlan:description': string;
      'customer:company:user:company:currentPlan:interval': 'monthly' | 'yearly' | 'custom';
      'customer:company:user:company:currentPlan:created_at': string;
      'customer:company:user:company:currentPlan:updated_at': string;
      'customer:company:currentPlan:id': number;
      'customer:company:currentPlan:name': string;
      'customer:company:currentPlan:price': number;
      'customer:company:currentPlan:description': string;
      'customer:company:currentPlan:interval': 'monthly' | 'yearly' | 'custom';
      'customer:company:currentPlan:created_at': string;
      'customer:company:currentPlan:updated_at': string;
      'company:id': number;
      'company:name': string;
      'company:industry': string;
      'company:size': number;
      'company:created_at': string;
      'company:updated_at': string;
      'company:user_id': number;
      'company:planId': number;
      'company:nbUsers': number;
      'company:planPrice': number;
      'company:MRR': number;
      'company:user:id': number;
      'company:user:firstname': string;
      'company:user:lastname': string;
      'company:user:email': string;
      'company:user:password': string;
      'company:user:avatar': string;
      'company:user:role': 'user' | 'editor' | 'admin';
      'company:user:status': 'enabled' | 'disabled' | 'deleted';
      'company:user:company_id': number;
      'company:user:created_at': string;
      'company:user:updated_at': string;
      'company:user:completed_at': string;
      'company:user:Fullname': string;
      'company:user:company:id': number;
      'company:user:company:name': string;
      'company:user:company:industry': string;
      'company:user:company:size': number;
      'company:user:company:created_at': string;
      'company:user:company:updated_at': string;
      'company:user:company:user_id': number;
      'company:user:company:planId': number;
      'company:user:company:nbUsers': number;
      'company:user:company:planPrice': number;
      'company:user:company:MRR': number;
      'company:user:company:user:id': number;
      'company:user:company:user:firstname': string;
      'company:user:company:user:lastname': string;
      'company:user:company:user:email': string;
      'company:user:company:user:password': string;
      'company:user:company:user:avatar': string;
      'company:user:company:user:role': 'user' | 'editor' | 'admin';
      'company:user:company:user:status': 'enabled' | 'disabled' | 'deleted';
      'company:user:company:user:company_id': number;
      'company:user:company:user:created_at': string;
      'company:user:company:user:updated_at': string;
      'company:user:company:user:completed_at': string;
      'company:user:company:user:Fullname': string;
      'company:user:company:user:company:id': number;
      'company:user:company:user:company:name': string;
      'company:user:company:user:company:industry': string;
      'company:user:company:user:company:size': number;
      'company:user:company:user:company:created_at': string;
      'company:user:company:user:company:updated_at': string;
      'company:user:company:user:company:user_id': number;
      'company:user:company:user:company:planId': number;
      'company:user:company:user:company:nbUsers': number;
      'company:user:company:user:company:planPrice': number;
      'company:user:company:user:company:MRR': number;
      'company:user:company:currentPlan:id': number;
      'company:user:company:currentPlan:name': string;
      'company:user:company:currentPlan:price': number;
      'company:user:company:currentPlan:description': string;
      'company:user:company:currentPlan:interval': 'monthly' | 'yearly' | 'custom';
      'company:user:company:currentPlan:created_at': string;
      'company:user:company:currentPlan:updated_at': string;
      'company:currentPlan:id': number;
      'company:currentPlan:name': string;
      'company:currentPlan:price': number;
      'company:currentPlan:description': string;
      'company:currentPlan:interval': 'monthly' | 'yearly' | 'custom';
      'company:currentPlan:created_at': string;
      'company:currentPlan:updated_at': string;
      'feature:id': number;
      'feature:name': string;
      'feature:description': string;
      'feature:plan_free': boolean;
      'feature:plan_team': boolean;
      'feature:plan_pro': boolean;
      'feature:plan_enterprise': boolean;
      'feature:created_at': string;
      'feature:updated_at': string;
    };
  };
  'companies': {
    plain: {
      'id': number;
      'name': string;
      'industry': string;
      'size': number;
      'created_at': string;
      'updated_at': string;
      'user_id': number;
      'planId': number;
      'nbUsers': number;
      'planPrice': number;
      'MRR': number;
    };
    nested: {
      'user': Schema['users']['plain'] & Schema['users']['nested'];
      'currentPlan': Schema['plans']['plain'] & Schema['plans']['nested'];
    };
    flat: {
      'user:id': number;
      'user:firstname': string;
      'user:lastname': string;
      'user:email': string;
      'user:password': string;
      'user:avatar': string;
      'user:role': 'user' | 'editor' | 'admin';
      'user:status': 'enabled' | 'disabled' | 'deleted';
      'user:company_id': number;
      'user:created_at': string;
      'user:updated_at': string;
      'user:completed_at': string;
      'user:Fullname': string;
      'user:company:id': number;
      'user:company:name': string;
      'user:company:industry': string;
      'user:company:size': number;
      'user:company:created_at': string;
      'user:company:updated_at': string;
      'user:company:user_id': number;
      'user:company:planId': number;
      'user:company:nbUsers': number;
      'user:company:planPrice': number;
      'user:company:MRR': number;
      'user:company:user:id': number;
      'user:company:user:firstname': string;
      'user:company:user:lastname': string;
      'user:company:user:email': string;
      'user:company:user:password': string;
      'user:company:user:avatar': string;
      'user:company:user:role': 'user' | 'editor' | 'admin';
      'user:company:user:status': 'enabled' | 'disabled' | 'deleted';
      'user:company:user:company_id': number;
      'user:company:user:created_at': string;
      'user:company:user:updated_at': string;
      'user:company:user:completed_at': string;
      'user:company:user:Fullname': string;
      'user:company:user:company:id': number;
      'user:company:user:company:name': string;
      'user:company:user:company:industry': string;
      'user:company:user:company:size': number;
      'user:company:user:company:created_at': string;
      'user:company:user:company:updated_at': string;
      'user:company:user:company:user_id': number;
      'user:company:user:company:planId': number;
      'user:company:user:company:nbUsers': number;
      'user:company:user:company:planPrice': number;
      'user:company:user:company:MRR': number;
      'user:company:user:company:user:id': number;
      'user:company:user:company:user:firstname': string;
      'user:company:user:company:user:lastname': string;
      'user:company:user:company:user:email': string;
      'user:company:user:company:user:password': string;
      'user:company:user:company:user:avatar': string;
      'user:company:user:company:user:role': 'user' | 'editor' | 'admin';
      'user:company:user:company:user:status': 'enabled' | 'disabled' | 'deleted';
      'user:company:user:company:user:company_id': number;
      'user:company:user:company:user:created_at': string;
      'user:company:user:company:user:updated_at': string;
      'user:company:user:company:user:completed_at': string;
      'user:company:user:company:user:Fullname': string;
      'user:company:user:company:currentPlan:id': number;
      'user:company:user:company:currentPlan:name': string;
      'user:company:user:company:currentPlan:price': number;
      'user:company:user:company:currentPlan:description': string;
      'user:company:user:company:currentPlan:interval': 'monthly' | 'yearly' | 'custom';
      'user:company:user:company:currentPlan:created_at': string;
      'user:company:user:company:currentPlan:updated_at': string;
      'user:company:currentPlan:id': number;
      'user:company:currentPlan:name': string;
      'user:company:currentPlan:price': number;
      'user:company:currentPlan:description': string;
      'user:company:currentPlan:interval': 'monthly' | 'yearly' | 'custom';
      'user:company:currentPlan:created_at': string;
      'user:company:currentPlan:updated_at': string;
      'currentPlan:id': number;
      'currentPlan:name': string;
      'currentPlan:price': number;
      'currentPlan:description': string;
      'currentPlan:interval': 'monthly' | 'yearly' | 'custom';
      'currentPlan:created_at': string;
      'currentPlan:updated_at': string;
    };
  };
  'features': {
    plain: {
      'id': number;
      'name': string;
      'description': string;
      'plan_free': boolean;
      'plan_team': boolean;
      'plan_pro': boolean;
      'plan_enterprise': boolean;
      'created_at': string;
      'updated_at': string;
    };
    nested: {};
    flat: {};
  };
  'invoices': {
    plain: {
      'id': number;
      'customer_id': number;
      'company_id': number;
      'subscription_id': number;
      'plan_id': number;
      'amount': number;
      'status': 'pending' | 'paid' | 'void';
      'created_at': string;
      'updated_at': string;
    };
    nested: {
      'customer': Schema['users']['plain'] & Schema['users']['nested'];
      'company': Schema['companies']['plain'] & Schema['companies']['nested'];
      'subscription': Schema['subscriptions']['plain'] & Schema['subscriptions']['nested'];
      'plan': Schema['plans']['plain'] & Schema['plans']['nested'];
    };
    flat: {
      'customer:id': number;
      'customer:firstname': string;
      'customer:lastname': string;
      'customer:email': string;
      'customer:password': string;
      'customer:avatar': string;
      'customer:role': 'user' | 'editor' | 'admin';
      'customer:status': 'enabled' | 'disabled' | 'deleted';
      'customer:company_id': number;
      'customer:created_at': string;
      'customer:updated_at': string;
      'customer:completed_at': string;
      'customer:Fullname': string;
      'customer:company:id': number;
      'customer:company:name': string;
      'customer:company:industry': string;
      'customer:company:size': number;
      'customer:company:created_at': string;
      'customer:company:updated_at': string;
      'customer:company:user_id': number;
      'customer:company:planId': number;
      'customer:company:nbUsers': number;
      'customer:company:planPrice': number;
      'customer:company:MRR': number;
      'customer:company:user:id': number;
      'customer:company:user:firstname': string;
      'customer:company:user:lastname': string;
      'customer:company:user:email': string;
      'customer:company:user:password': string;
      'customer:company:user:avatar': string;
      'customer:company:user:role': 'user' | 'editor' | 'admin';
      'customer:company:user:status': 'enabled' | 'disabled' | 'deleted';
      'customer:company:user:company_id': number;
      'customer:company:user:created_at': string;
      'customer:company:user:updated_at': string;
      'customer:company:user:completed_at': string;
      'customer:company:user:Fullname': string;
      'customer:company:user:company:id': number;
      'customer:company:user:company:name': string;
      'customer:company:user:company:industry': string;
      'customer:company:user:company:size': number;
      'customer:company:user:company:created_at': string;
      'customer:company:user:company:updated_at': string;
      'customer:company:user:company:user_id': number;
      'customer:company:user:company:planId': number;
      'customer:company:user:company:nbUsers': number;
      'customer:company:user:company:planPrice': number;
      'customer:company:user:company:MRR': number;
      'customer:company:user:company:user:id': number;
      'customer:company:user:company:user:firstname': string;
      'customer:company:user:company:user:lastname': string;
      'customer:company:user:company:user:email': string;
      'customer:company:user:company:user:password': string;
      'customer:company:user:company:user:avatar': string;
      'customer:company:user:company:user:role': 'user' | 'editor' | 'admin';
      'customer:company:user:company:user:status': 'enabled' | 'disabled' | 'deleted';
      'customer:company:user:company:user:company_id': number;
      'customer:company:user:company:user:created_at': string;
      'customer:company:user:company:user:updated_at': string;
      'customer:company:user:company:user:completed_at': string;
      'customer:company:user:company:user:Fullname': string;
      'customer:company:user:company:currentPlan:id': number;
      'customer:company:user:company:currentPlan:name': string;
      'customer:company:user:company:currentPlan:price': number;
      'customer:company:user:company:currentPlan:description': string;
      'customer:company:user:company:currentPlan:interval': 'monthly' | 'yearly' | 'custom';
      'customer:company:user:company:currentPlan:created_at': string;
      'customer:company:user:company:currentPlan:updated_at': string;
      'customer:company:currentPlan:id': number;
      'customer:company:currentPlan:name': string;
      'customer:company:currentPlan:price': number;
      'customer:company:currentPlan:description': string;
      'customer:company:currentPlan:interval': 'monthly' | 'yearly' | 'custom';
      'customer:company:currentPlan:created_at': string;
      'customer:company:currentPlan:updated_at': string;
      'company:id': number;
      'company:name': string;
      'company:industry': string;
      'company:size': number;
      'company:created_at': string;
      'company:updated_at': string;
      'company:user_id': number;
      'company:planId': number;
      'company:nbUsers': number;
      'company:planPrice': number;
      'company:MRR': number;
      'company:user:id': number;
      'company:user:firstname': string;
      'company:user:lastname': string;
      'company:user:email': string;
      'company:user:password': string;
      'company:user:avatar': string;
      'company:user:role': 'user' | 'editor' | 'admin';
      'company:user:status': 'enabled' | 'disabled' | 'deleted';
      'company:user:company_id': number;
      'company:user:created_at': string;
      'company:user:updated_at': string;
      'company:user:completed_at': string;
      'company:user:Fullname': string;
      'company:user:company:id': number;
      'company:user:company:name': string;
      'company:user:company:industry': string;
      'company:user:company:size': number;
      'company:user:company:created_at': string;
      'company:user:company:updated_at': string;
      'company:user:company:user_id': number;
      'company:user:company:planId': number;
      'company:user:company:nbUsers': number;
      'company:user:company:planPrice': number;
      'company:user:company:MRR': number;
      'company:user:company:user:id': number;
      'company:user:company:user:firstname': string;
      'company:user:company:user:lastname': string;
      'company:user:company:user:email': string;
      'company:user:company:user:password': string;
      'company:user:company:user:avatar': string;
      'company:user:company:user:role': 'user' | 'editor' | 'admin';
      'company:user:company:user:status': 'enabled' | 'disabled' | 'deleted';
      'company:user:company:user:company_id': number;
      'company:user:company:user:created_at': string;
      'company:user:company:user:updated_at': string;
      'company:user:company:user:completed_at': string;
      'company:user:company:user:Fullname': string;
      'company:user:company:user:company:id': number;
      'company:user:company:user:company:name': string;
      'company:user:company:user:company:industry': string;
      'company:user:company:user:company:size': number;
      'company:user:company:user:company:created_at': string;
      'company:user:company:user:company:updated_at': string;
      'company:user:company:user:company:user_id': number;
      'company:user:company:user:company:planId': number;
      'company:user:company:user:company:nbUsers': number;
      'company:user:company:user:company:planPrice': number;
      'company:user:company:user:company:MRR': number;
      'company:user:company:currentPlan:id': number;
      'company:user:company:currentPlan:name': string;
      'company:user:company:currentPlan:price': number;
      'company:user:company:currentPlan:description': string;
      'company:user:company:currentPlan:interval': 'monthly' | 'yearly' | 'custom';
      'company:user:company:currentPlan:created_at': string;
      'company:user:company:currentPlan:updated_at': string;
      'company:currentPlan:id': number;
      'company:currentPlan:name': string;
      'company:currentPlan:price': number;
      'company:currentPlan:description': string;
      'company:currentPlan:interval': 'monthly' | 'yearly' | 'custom';
      'company:currentPlan:created_at': string;
      'company:currentPlan:updated_at': string;
      'subscription:id': number;
      'subscription:customer_id': number;
      'subscription:company_id': number;
      'subscription:plan_id': number;
      'subscription:started_at': string;
      'subscription:ended_at': string;
      'subscription:renewal_date': string;
      'subscription:discount': number;
      'subscription:created_at': string;
      'subscription:updated_at': string;
      'subscription:commitment': 'monthly' | 'yearly';
      'subscription:status': 'active' | 'paused' | 'canceled';
      'subscription:customer:id': number;
      'subscription:customer:firstname': string;
      'subscription:customer:lastname': string;
      'subscription:customer:email': string;
      'subscription:customer:password': string;
      'subscription:customer:avatar': string;
      'subscription:customer:role': 'user' | 'editor' | 'admin';
      'subscription:customer:status': 'enabled' | 'disabled' | 'deleted';
      'subscription:customer:company_id': number;
      'subscription:customer:created_at': string;
      'subscription:customer:updated_at': string;
      'subscription:customer:completed_at': string;
      'subscription:customer:Fullname': string;
      'subscription:customer:company:id': number;
      'subscription:customer:company:name': string;
      'subscription:customer:company:industry': string;
      'subscription:customer:company:size': number;
      'subscription:customer:company:created_at': string;
      'subscription:customer:company:updated_at': string;
      'subscription:customer:company:user_id': number;
      'subscription:customer:company:planId': number;
      'subscription:customer:company:nbUsers': number;
      'subscription:customer:company:planPrice': number;
      'subscription:customer:company:MRR': number;
      'subscription:customer:company:user:id': number;
      'subscription:customer:company:user:firstname': string;
      'subscription:customer:company:user:lastname': string;
      'subscription:customer:company:user:email': string;
      'subscription:customer:company:user:password': string;
      'subscription:customer:company:user:avatar': string;
      'subscription:customer:company:user:role': 'user' | 'editor' | 'admin';
      'subscription:customer:company:user:status': 'enabled' | 'disabled' | 'deleted';
      'subscription:customer:company:user:company_id': number;
      'subscription:customer:company:user:created_at': string;
      'subscription:customer:company:user:updated_at': string;
      'subscription:customer:company:user:completed_at': string;
      'subscription:customer:company:user:Fullname': string;
      'subscription:customer:company:user:company:id': number;
      'subscription:customer:company:user:company:name': string;
      'subscription:customer:company:user:company:industry': string;
      'subscription:customer:company:user:company:size': number;
      'subscription:customer:company:user:company:created_at': string;
      'subscription:customer:company:user:company:updated_at': string;
      'subscription:customer:company:user:company:user_id': number;
      'subscription:customer:company:user:company:planId': number;
      'subscription:customer:company:user:company:nbUsers': number;
      'subscription:customer:company:user:company:planPrice': number;
      'subscription:customer:company:user:company:MRR': number;
      'subscription:customer:company:currentPlan:id': number;
      'subscription:customer:company:currentPlan:name': string;
      'subscription:customer:company:currentPlan:price': number;
      'subscription:customer:company:currentPlan:description': string;
      'subscription:customer:company:currentPlan:interval': 'monthly' | 'yearly' | 'custom';
      'subscription:customer:company:currentPlan:created_at': string;
      'subscription:customer:company:currentPlan:updated_at': string;
      'subscription:company:id': number;
      'subscription:company:name': string;
      'subscription:company:industry': string;
      'subscription:company:size': number;
      'subscription:company:created_at': string;
      'subscription:company:updated_at': string;
      'subscription:company:user_id': number;
      'subscription:company:planId': number;
      'subscription:company:nbUsers': number;
      'subscription:company:planPrice': number;
      'subscription:company:MRR': number;
      'subscription:company:user:id': number;
      'subscription:company:user:firstname': string;
      'subscription:company:user:lastname': string;
      'subscription:company:user:email': string;
      'subscription:company:user:password': string;
      'subscription:company:user:avatar': string;
      'subscription:company:user:role': 'user' | 'editor' | 'admin';
      'subscription:company:user:status': 'enabled' | 'disabled' | 'deleted';
      'subscription:company:user:company_id': number;
      'subscription:company:user:created_at': string;
      'subscription:company:user:updated_at': string;
      'subscription:company:user:completed_at': string;
      'subscription:company:user:Fullname': string;
      'subscription:company:user:company:id': number;
      'subscription:company:user:company:name': string;
      'subscription:company:user:company:industry': string;
      'subscription:company:user:company:size': number;
      'subscription:company:user:company:created_at': string;
      'subscription:company:user:company:updated_at': string;
      'subscription:company:user:company:user_id': number;
      'subscription:company:user:company:planId': number;
      'subscription:company:user:company:nbUsers': number;
      'subscription:company:user:company:planPrice': number;
      'subscription:company:user:company:MRR': number;
      'subscription:company:user:company:user:id': number;
      'subscription:company:user:company:user:firstname': string;
      'subscription:company:user:company:user:lastname': string;
      'subscription:company:user:company:user:email': string;
      'subscription:company:user:company:user:password': string;
      'subscription:company:user:company:user:avatar': string;
      'subscription:company:user:company:user:role': 'user' | 'editor' | 'admin';
      'subscription:company:user:company:user:status': 'enabled' | 'disabled' | 'deleted';
      'subscription:company:user:company:user:company_id': number;
      'subscription:company:user:company:user:created_at': string;
      'subscription:company:user:company:user:updated_at': string;
      'subscription:company:user:company:user:completed_at': string;
      'subscription:company:user:company:user:Fullname': string;
      'subscription:company:user:company:currentPlan:id': number;
      'subscription:company:user:company:currentPlan:name': string;
      'subscription:company:user:company:currentPlan:price': number;
      'subscription:company:user:company:currentPlan:description': string;
      'subscription:company:user:company:currentPlan:interval': 'monthly' | 'yearly' | 'custom';
      'subscription:company:user:company:currentPlan:created_at': string;
      'subscription:company:user:company:currentPlan:updated_at': string;
      'subscription:company:currentPlan:id': number;
      'subscription:company:currentPlan:name': string;
      'subscription:company:currentPlan:price': number;
      'subscription:company:currentPlan:description': string;
      'subscription:company:currentPlan:interval': 'monthly' | 'yearly' | 'custom';
      'subscription:company:currentPlan:created_at': string;
      'subscription:company:currentPlan:updated_at': string;
      'subscription:plan:id': number;
      'subscription:plan:name': string;
      'subscription:plan:price': number;
      'subscription:plan:description': string;
      'subscription:plan:interval': 'monthly' | 'yearly' | 'custom';
      'subscription:plan:created_at': string;
      'subscription:plan:updated_at': string;
      'plan:id': number;
      'plan:name': string;
      'plan:price': number;
      'plan:description': string;
      'plan:interval': 'monthly' | 'yearly' | 'custom';
      'plan:created_at': string;
      'plan:updated_at': string;
    };
  };
  'plans': {
    plain: {
      'id': number;
      'name': string;
      'price': number;
      'description': string;
      'interval': 'monthly' | 'yearly' | 'custom';
      'created_at': string;
      'updated_at': string;
    };
    nested: {};
    flat: {};
  };
  'subscriptions': {
    plain: {
      'id': number;
      'customer_id': number;
      'company_id': number;
      'plan_id': number;
      'started_at': string;
      'ended_at': string;
      'renewal_date': string;
      'discount': number;
      'created_at': string;
      'updated_at': string;
      'commitment': 'monthly' | 'yearly';
      'status': 'active' | 'paused' | 'canceled';
    };
    nested: {
      'customer': Schema['users']['plain'] & Schema['users']['nested'];
      'company': Schema['companies']['plain'] & Schema['companies']['nested'];
      'plan': Schema['plans']['plain'] & Schema['plans']['nested'];
    };
    flat: {
      'customer:id': number;
      'customer:firstname': string;
      'customer:lastname': string;
      'customer:email': string;
      'customer:password': string;
      'customer:avatar': string;
      'customer:role': 'user' | 'editor' | 'admin';
      'customer:status': 'enabled' | 'disabled' | 'deleted';
      'customer:company_id': number;
      'customer:created_at': string;
      'customer:updated_at': string;
      'customer:completed_at': string;
      'customer:Fullname': string;
      'customer:company:id': number;
      'customer:company:name': string;
      'customer:company:industry': string;
      'customer:company:size': number;
      'customer:company:created_at': string;
      'customer:company:updated_at': string;
      'customer:company:user_id': number;
      'customer:company:planId': number;
      'customer:company:nbUsers': number;
      'customer:company:planPrice': number;
      'customer:company:MRR': number;
      'customer:company:user:id': number;
      'customer:company:user:firstname': string;
      'customer:company:user:lastname': string;
      'customer:company:user:email': string;
      'customer:company:user:password': string;
      'customer:company:user:avatar': string;
      'customer:company:user:role': 'user' | 'editor' | 'admin';
      'customer:company:user:status': 'enabled' | 'disabled' | 'deleted';
      'customer:company:user:company_id': number;
      'customer:company:user:created_at': string;
      'customer:company:user:updated_at': string;
      'customer:company:user:completed_at': string;
      'customer:company:user:Fullname': string;
      'customer:company:user:company:id': number;
      'customer:company:user:company:name': string;
      'customer:company:user:company:industry': string;
      'customer:company:user:company:size': number;
      'customer:company:user:company:created_at': string;
      'customer:company:user:company:updated_at': string;
      'customer:company:user:company:user_id': number;
      'customer:company:user:company:planId': number;
      'customer:company:user:company:nbUsers': number;
      'customer:company:user:company:planPrice': number;
      'customer:company:user:company:MRR': number;
      'customer:company:user:company:user:id': number;
      'customer:company:user:company:user:firstname': string;
      'customer:company:user:company:user:lastname': string;
      'customer:company:user:company:user:email': string;
      'customer:company:user:company:user:password': string;
      'customer:company:user:company:user:avatar': string;
      'customer:company:user:company:user:role': 'user' | 'editor' | 'admin';
      'customer:company:user:company:user:status': 'enabled' | 'disabled' | 'deleted';
      'customer:company:user:company:user:company_id': number;
      'customer:company:user:company:user:created_at': string;
      'customer:company:user:company:user:updated_at': string;
      'customer:company:user:company:user:completed_at': string;
      'customer:company:user:company:user:Fullname': string;
      'customer:company:user:company:currentPlan:id': number;
      'customer:company:user:company:currentPlan:name': string;
      'customer:company:user:company:currentPlan:price': number;
      'customer:company:user:company:currentPlan:description': string;
      'customer:company:user:company:currentPlan:interval': 'monthly' | 'yearly' | 'custom';
      'customer:company:user:company:currentPlan:created_at': string;
      'customer:company:user:company:currentPlan:updated_at': string;
      'customer:company:currentPlan:id': number;
      'customer:company:currentPlan:name': string;
      'customer:company:currentPlan:price': number;
      'customer:company:currentPlan:description': string;
      'customer:company:currentPlan:interval': 'monthly' | 'yearly' | 'custom';
      'customer:company:currentPlan:created_at': string;
      'customer:company:currentPlan:updated_at': string;
      'company:id': number;
      'company:name': string;
      'company:industry': string;
      'company:size': number;
      'company:created_at': string;
      'company:updated_at': string;
      'company:user_id': number;
      'company:planId': number;
      'company:nbUsers': number;
      'company:planPrice': number;
      'company:MRR': number;
      'company:user:id': number;
      'company:user:firstname': string;
      'company:user:lastname': string;
      'company:user:email': string;
      'company:user:password': string;
      'company:user:avatar': string;
      'company:user:role': 'user' | 'editor' | 'admin';
      'company:user:status': 'enabled' | 'disabled' | 'deleted';
      'company:user:company_id': number;
      'company:user:created_at': string;
      'company:user:updated_at': string;
      'company:user:completed_at': string;
      'company:user:Fullname': string;
      'company:user:company:id': number;
      'company:user:company:name': string;
      'company:user:company:industry': string;
      'company:user:company:size': number;
      'company:user:company:created_at': string;
      'company:user:company:updated_at': string;
      'company:user:company:user_id': number;
      'company:user:company:planId': number;
      'company:user:company:nbUsers': number;
      'company:user:company:planPrice': number;
      'company:user:company:MRR': number;
      'company:user:company:user:id': number;
      'company:user:company:user:firstname': string;
      'company:user:company:user:lastname': string;
      'company:user:company:user:email': string;
      'company:user:company:user:password': string;
      'company:user:company:user:avatar': string;
      'company:user:company:user:role': 'user' | 'editor' | 'admin';
      'company:user:company:user:status': 'enabled' | 'disabled' | 'deleted';
      'company:user:company:user:company_id': number;
      'company:user:company:user:created_at': string;
      'company:user:company:user:updated_at': string;
      'company:user:company:user:completed_at': string;
      'company:user:company:user:Fullname': string;
      'company:user:company:user:company:id': number;
      'company:user:company:user:company:name': string;
      'company:user:company:user:company:industry': string;
      'company:user:company:user:company:size': number;
      'company:user:company:user:company:created_at': string;
      'company:user:company:user:company:updated_at': string;
      'company:user:company:user:company:user_id': number;
      'company:user:company:user:company:planId': number;
      'company:user:company:user:company:nbUsers': number;
      'company:user:company:user:company:planPrice': number;
      'company:user:company:user:company:MRR': number;
      'company:user:company:currentPlan:id': number;
      'company:user:company:currentPlan:name': string;
      'company:user:company:currentPlan:price': number;
      'company:user:company:currentPlan:description': string;
      'company:user:company:currentPlan:interval': 'monthly' | 'yearly' | 'custom';
      'company:user:company:currentPlan:created_at': string;
      'company:user:company:currentPlan:updated_at': string;
      'company:currentPlan:id': number;
      'company:currentPlan:name': string;
      'company:currentPlan:price': number;
      'company:currentPlan:description': string;
      'company:currentPlan:interval': 'monthly' | 'yearly' | 'custom';
      'company:currentPlan:created_at': string;
      'company:currentPlan:updated_at': string;
      'plan:id': number;
      'plan:name': string;
      'plan:price': number;
      'plan:description': string;
      'plan:interval': 'monthly' | 'yearly' | 'custom';
      'plan:created_at': string;
      'plan:updated_at': string;
    };
  };
  'support_tickets': {
    plain: {
      'id': number;
      'customer_id': number;
      'company_id': number;
      'issue_topic': string;
      'status': 'new' | 'assigned' | 'closed';
      'created_at': string;
      'updated_at': string;
      'closed_at': string;
    };
    nested: {
      'customer': Schema['users']['plain'] & Schema['users']['nested'];
      'company': Schema['companies']['plain'] & Schema['companies']['nested'];
    };
    flat: {
      'customer:id': number;
      'customer:firstname': string;
      'customer:lastname': string;
      'customer:email': string;
      'customer:password': string;
      'customer:avatar': string;
      'customer:role': 'user' | 'editor' | 'admin';
      'customer:status': 'enabled' | 'disabled' | 'deleted';
      'customer:company_id': number;
      'customer:created_at': string;
      'customer:updated_at': string;
      'customer:completed_at': string;
      'customer:Fullname': string;
      'customer:company:id': number;
      'customer:company:name': string;
      'customer:company:industry': string;
      'customer:company:size': number;
      'customer:company:created_at': string;
      'customer:company:updated_at': string;
      'customer:company:user_id': number;
      'customer:company:planId': number;
      'customer:company:nbUsers': number;
      'customer:company:planPrice': number;
      'customer:company:MRR': number;
      'customer:company:user:id': number;
      'customer:company:user:firstname': string;
      'customer:company:user:lastname': string;
      'customer:company:user:email': string;
      'customer:company:user:password': string;
      'customer:company:user:avatar': string;
      'customer:company:user:role': 'user' | 'editor' | 'admin';
      'customer:company:user:status': 'enabled' | 'disabled' | 'deleted';
      'customer:company:user:company_id': number;
      'customer:company:user:created_at': string;
      'customer:company:user:updated_at': string;
      'customer:company:user:completed_at': string;
      'customer:company:user:Fullname': string;
      'customer:company:user:company:id': number;
      'customer:company:user:company:name': string;
      'customer:company:user:company:industry': string;
      'customer:company:user:company:size': number;
      'customer:company:user:company:created_at': string;
      'customer:company:user:company:updated_at': string;
      'customer:company:user:company:user_id': number;
      'customer:company:user:company:planId': number;
      'customer:company:user:company:nbUsers': number;
      'customer:company:user:company:planPrice': number;
      'customer:company:user:company:MRR': number;
      'customer:company:user:company:user:id': number;
      'customer:company:user:company:user:firstname': string;
      'customer:company:user:company:user:lastname': string;
      'customer:company:user:company:user:email': string;
      'customer:company:user:company:user:password': string;
      'customer:company:user:company:user:avatar': string;
      'customer:company:user:company:user:role': 'user' | 'editor' | 'admin';
      'customer:company:user:company:user:status': 'enabled' | 'disabled' | 'deleted';
      'customer:company:user:company:user:company_id': number;
      'customer:company:user:company:user:created_at': string;
      'customer:company:user:company:user:updated_at': string;
      'customer:company:user:company:user:completed_at': string;
      'customer:company:user:company:user:Fullname': string;
      'customer:company:user:company:currentPlan:id': number;
      'customer:company:user:company:currentPlan:name': string;
      'customer:company:user:company:currentPlan:price': number;
      'customer:company:user:company:currentPlan:description': string;
      'customer:company:user:company:currentPlan:interval': 'monthly' | 'yearly' | 'custom';
      'customer:company:user:company:currentPlan:created_at': string;
      'customer:company:user:company:currentPlan:updated_at': string;
      'customer:company:currentPlan:id': number;
      'customer:company:currentPlan:name': string;
      'customer:company:currentPlan:price': number;
      'customer:company:currentPlan:description': string;
      'customer:company:currentPlan:interval': 'monthly' | 'yearly' | 'custom';
      'customer:company:currentPlan:created_at': string;
      'customer:company:currentPlan:updated_at': string;
      'company:id': number;
      'company:name': string;
      'company:industry': string;
      'company:size': number;
      'company:created_at': string;
      'company:updated_at': string;
      'company:user_id': number;
      'company:planId': number;
      'company:nbUsers': number;
      'company:planPrice': number;
      'company:MRR': number;
      'company:user:id': number;
      'company:user:firstname': string;
      'company:user:lastname': string;
      'company:user:email': string;
      'company:user:password': string;
      'company:user:avatar': string;
      'company:user:role': 'user' | 'editor' | 'admin';
      'company:user:status': 'enabled' | 'disabled' | 'deleted';
      'company:user:company_id': number;
      'company:user:created_at': string;
      'company:user:updated_at': string;
      'company:user:completed_at': string;
      'company:user:Fullname': string;
      'company:user:company:id': number;
      'company:user:company:name': string;
      'company:user:company:industry': string;
      'company:user:company:size': number;
      'company:user:company:created_at': string;
      'company:user:company:updated_at': string;
      'company:user:company:user_id': number;
      'company:user:company:planId': number;
      'company:user:company:nbUsers': number;
      'company:user:company:planPrice': number;
      'company:user:company:MRR': number;
      'company:user:company:user:id': number;
      'company:user:company:user:firstname': string;
      'company:user:company:user:lastname': string;
      'company:user:company:user:email': string;
      'company:user:company:user:password': string;
      'company:user:company:user:avatar': string;
      'company:user:company:user:role': 'user' | 'editor' | 'admin';
      'company:user:company:user:status': 'enabled' | 'disabled' | 'deleted';
      'company:user:company:user:company_id': number;
      'company:user:company:user:created_at': string;
      'company:user:company:user:updated_at': string;
      'company:user:company:user:completed_at': string;
      'company:user:company:user:Fullname': string;
      'company:user:company:user:company:id': number;
      'company:user:company:user:company:name': string;
      'company:user:company:user:company:industry': string;
      'company:user:company:user:company:size': number;
      'company:user:company:user:company:created_at': string;
      'company:user:company:user:company:updated_at': string;
      'company:user:company:user:company:user_id': number;
      'company:user:company:user:company:planId': number;
      'company:user:company:user:company:nbUsers': number;
      'company:user:company:user:company:planPrice': number;
      'company:user:company:user:company:MRR': number;
      'company:user:company:currentPlan:id': number;
      'company:user:company:currentPlan:name': string;
      'company:user:company:currentPlan:price': number;
      'company:user:company:currentPlan:description': string;
      'company:user:company:currentPlan:interval': 'monthly' | 'yearly' | 'custom';
      'company:user:company:currentPlan:created_at': string;
      'company:user:company:currentPlan:updated_at': string;
      'company:currentPlan:id': number;
      'company:currentPlan:name': string;
      'company:currentPlan:price': number;
      'company:currentPlan:description': string;
      'company:currentPlan:interval': 'monthly' | 'yearly' | 'custom';
      'company:currentPlan:created_at': string;
      'company:currentPlan:updated_at': string;
    };
  };
  'transactions': {
    plain: {
      'id': number;
      'customer_id': number;
      'company_id': number;
      'invoice_id': number;
      'amount': number;
      'payment_method': 'credit_card' | 'paypal' | 'stripe' | 'bank_transfer';
      'executed_at': string;
    };
    nested: {
      'customer': Schema['users']['plain'] & Schema['users']['nested'];
      'company': Schema['companies']['plain'] & Schema['companies']['nested'];
      'invoice': Schema['invoices']['plain'] & Schema['invoices']['nested'];
    };
    flat: {
      'customer:id': number;
      'customer:firstname': string;
      'customer:lastname': string;
      'customer:email': string;
      'customer:password': string;
      'customer:avatar': string;
      'customer:role': 'user' | 'editor' | 'admin';
      'customer:status': 'enabled' | 'disabled' | 'deleted';
      'customer:company_id': number;
      'customer:created_at': string;
      'customer:updated_at': string;
      'customer:completed_at': string;
      'customer:Fullname': string;
      'customer:company:id': number;
      'customer:company:name': string;
      'customer:company:industry': string;
      'customer:company:size': number;
      'customer:company:created_at': string;
      'customer:company:updated_at': string;
      'customer:company:user_id': number;
      'customer:company:planId': number;
      'customer:company:nbUsers': number;
      'customer:company:planPrice': number;
      'customer:company:MRR': number;
      'customer:company:user:id': number;
      'customer:company:user:firstname': string;
      'customer:company:user:lastname': string;
      'customer:company:user:email': string;
      'customer:company:user:password': string;
      'customer:company:user:avatar': string;
      'customer:company:user:role': 'user' | 'editor' | 'admin';
      'customer:company:user:status': 'enabled' | 'disabled' | 'deleted';
      'customer:company:user:company_id': number;
      'customer:company:user:created_at': string;
      'customer:company:user:updated_at': string;
      'customer:company:user:completed_at': string;
      'customer:company:user:Fullname': string;
      'customer:company:user:company:id': number;
      'customer:company:user:company:name': string;
      'customer:company:user:company:industry': string;
      'customer:company:user:company:size': number;
      'customer:company:user:company:created_at': string;
      'customer:company:user:company:updated_at': string;
      'customer:company:user:company:user_id': number;
      'customer:company:user:company:planId': number;
      'customer:company:user:company:nbUsers': number;
      'customer:company:user:company:planPrice': number;
      'customer:company:user:company:MRR': number;
      'customer:company:user:company:user:id': number;
      'customer:company:user:company:user:firstname': string;
      'customer:company:user:company:user:lastname': string;
      'customer:company:user:company:user:email': string;
      'customer:company:user:company:user:password': string;
      'customer:company:user:company:user:avatar': string;
      'customer:company:user:company:user:role': 'user' | 'editor' | 'admin';
      'customer:company:user:company:user:status': 'enabled' | 'disabled' | 'deleted';
      'customer:company:user:company:user:company_id': number;
      'customer:company:user:company:user:created_at': string;
      'customer:company:user:company:user:updated_at': string;
      'customer:company:user:company:user:completed_at': string;
      'customer:company:user:company:user:Fullname': string;
      'customer:company:user:company:currentPlan:id': number;
      'customer:company:user:company:currentPlan:name': string;
      'customer:company:user:company:currentPlan:price': number;
      'customer:company:user:company:currentPlan:description': string;
      'customer:company:user:company:currentPlan:interval': 'monthly' | 'yearly' | 'custom';
      'customer:company:user:company:currentPlan:created_at': string;
      'customer:company:user:company:currentPlan:updated_at': string;
      'customer:company:currentPlan:id': number;
      'customer:company:currentPlan:name': string;
      'customer:company:currentPlan:price': number;
      'customer:company:currentPlan:description': string;
      'customer:company:currentPlan:interval': 'monthly' | 'yearly' | 'custom';
      'customer:company:currentPlan:created_at': string;
      'customer:company:currentPlan:updated_at': string;
      'company:id': number;
      'company:name': string;
      'company:industry': string;
      'company:size': number;
      'company:created_at': string;
      'company:updated_at': string;
      'company:user_id': number;
      'company:planId': number;
      'company:nbUsers': number;
      'company:planPrice': number;
      'company:MRR': number;
      'company:user:id': number;
      'company:user:firstname': string;
      'company:user:lastname': string;
      'company:user:email': string;
      'company:user:password': string;
      'company:user:avatar': string;
      'company:user:role': 'user' | 'editor' | 'admin';
      'company:user:status': 'enabled' | 'disabled' | 'deleted';
      'company:user:company_id': number;
      'company:user:created_at': string;
      'company:user:updated_at': string;
      'company:user:completed_at': string;
      'company:user:Fullname': string;
      'company:user:company:id': number;
      'company:user:company:name': string;
      'company:user:company:industry': string;
      'company:user:company:size': number;
      'company:user:company:created_at': string;
      'company:user:company:updated_at': string;
      'company:user:company:user_id': number;
      'company:user:company:planId': number;
      'company:user:company:nbUsers': number;
      'company:user:company:planPrice': number;
      'company:user:company:MRR': number;
      'company:user:company:user:id': number;
      'company:user:company:user:firstname': string;
      'company:user:company:user:lastname': string;
      'company:user:company:user:email': string;
      'company:user:company:user:password': string;
      'company:user:company:user:avatar': string;
      'company:user:company:user:role': 'user' | 'editor' | 'admin';
      'company:user:company:user:status': 'enabled' | 'disabled' | 'deleted';
      'company:user:company:user:company_id': number;
      'company:user:company:user:created_at': string;
      'company:user:company:user:updated_at': string;
      'company:user:company:user:completed_at': string;
      'company:user:company:user:Fullname': string;
      'company:user:company:user:company:id': number;
      'company:user:company:user:company:name': string;
      'company:user:company:user:company:industry': string;
      'company:user:company:user:company:size': number;
      'company:user:company:user:company:created_at': string;
      'company:user:company:user:company:updated_at': string;
      'company:user:company:user:company:user_id': number;
      'company:user:company:user:company:planId': number;
      'company:user:company:user:company:nbUsers': number;
      'company:user:company:user:company:planPrice': number;
      'company:user:company:user:company:MRR': number;
      'company:user:company:currentPlan:id': number;
      'company:user:company:currentPlan:name': string;
      'company:user:company:currentPlan:price': number;
      'company:user:company:currentPlan:description': string;
      'company:user:company:currentPlan:interval': 'monthly' | 'yearly' | 'custom';
      'company:user:company:currentPlan:created_at': string;
      'company:user:company:currentPlan:updated_at': string;
      'company:currentPlan:id': number;
      'company:currentPlan:name': string;
      'company:currentPlan:price': number;
      'company:currentPlan:description': string;
      'company:currentPlan:interval': 'monthly' | 'yearly' | 'custom';
      'company:currentPlan:created_at': string;
      'company:currentPlan:updated_at': string;
      'invoice:id': number;
      'invoice:customer_id': number;
      'invoice:company_id': number;
      'invoice:subscription_id': number;
      'invoice:plan_id': number;
      'invoice:amount': number;
      'invoice:status': 'pending' | 'paid' | 'void';
      'invoice:created_at': string;
      'invoice:updated_at': string;
      'invoice:customer:id': number;
      'invoice:customer:firstname': string;
      'invoice:customer:lastname': string;
      'invoice:customer:email': string;
      'invoice:customer:password': string;
      'invoice:customer:avatar': string;
      'invoice:customer:role': 'user' | 'editor' | 'admin';
      'invoice:customer:status': 'enabled' | 'disabled' | 'deleted';
      'invoice:customer:company_id': number;
      'invoice:customer:created_at': string;
      'invoice:customer:updated_at': string;
      'invoice:customer:completed_at': string;
      'invoice:customer:Fullname': string;
      'invoice:customer:company:id': number;
      'invoice:customer:company:name': string;
      'invoice:customer:company:industry': string;
      'invoice:customer:company:size': number;
      'invoice:customer:company:created_at': string;
      'invoice:customer:company:updated_at': string;
      'invoice:customer:company:user_id': number;
      'invoice:customer:company:planId': number;
      'invoice:customer:company:nbUsers': number;
      'invoice:customer:company:planPrice': number;
      'invoice:customer:company:MRR': number;
      'invoice:customer:company:user:id': number;
      'invoice:customer:company:user:firstname': string;
      'invoice:customer:company:user:lastname': string;
      'invoice:customer:company:user:email': string;
      'invoice:customer:company:user:password': string;
      'invoice:customer:company:user:avatar': string;
      'invoice:customer:company:user:role': 'user' | 'editor' | 'admin';
      'invoice:customer:company:user:status': 'enabled' | 'disabled' | 'deleted';
      'invoice:customer:company:user:company_id': number;
      'invoice:customer:company:user:created_at': string;
      'invoice:customer:company:user:updated_at': string;
      'invoice:customer:company:user:completed_at': string;
      'invoice:customer:company:user:Fullname': string;
      'invoice:customer:company:user:company:id': number;
      'invoice:customer:company:user:company:name': string;
      'invoice:customer:company:user:company:industry': string;
      'invoice:customer:company:user:company:size': number;
      'invoice:customer:company:user:company:created_at': string;
      'invoice:customer:company:user:company:updated_at': string;
      'invoice:customer:company:user:company:user_id': number;
      'invoice:customer:company:user:company:planId': number;
      'invoice:customer:company:user:company:nbUsers': number;
      'invoice:customer:company:user:company:planPrice': number;
      'invoice:customer:company:user:company:MRR': number;
      'invoice:customer:company:currentPlan:id': number;
      'invoice:customer:company:currentPlan:name': string;
      'invoice:customer:company:currentPlan:price': number;
      'invoice:customer:company:currentPlan:description': string;
      'invoice:customer:company:currentPlan:interval': 'monthly' | 'yearly' | 'custom';
      'invoice:customer:company:currentPlan:created_at': string;
      'invoice:customer:company:currentPlan:updated_at': string;
      'invoice:company:id': number;
      'invoice:company:name': string;
      'invoice:company:industry': string;
      'invoice:company:size': number;
      'invoice:company:created_at': string;
      'invoice:company:updated_at': string;
      'invoice:company:user_id': number;
      'invoice:company:planId': number;
      'invoice:company:nbUsers': number;
      'invoice:company:planPrice': number;
      'invoice:company:MRR': number;
      'invoice:company:user:id': number;
      'invoice:company:user:firstname': string;
      'invoice:company:user:lastname': string;
      'invoice:company:user:email': string;
      'invoice:company:user:password': string;
      'invoice:company:user:avatar': string;
      'invoice:company:user:role': 'user' | 'editor' | 'admin';
      'invoice:company:user:status': 'enabled' | 'disabled' | 'deleted';
      'invoice:company:user:company_id': number;
      'invoice:company:user:created_at': string;
      'invoice:company:user:updated_at': string;
      'invoice:company:user:completed_at': string;
      'invoice:company:user:Fullname': string;
      'invoice:company:user:company:id': number;
      'invoice:company:user:company:name': string;
      'invoice:company:user:company:industry': string;
      'invoice:company:user:company:size': number;
      'invoice:company:user:company:created_at': string;
      'invoice:company:user:company:updated_at': string;
      'invoice:company:user:company:user_id': number;
      'invoice:company:user:company:planId': number;
      'invoice:company:user:company:nbUsers': number;
      'invoice:company:user:company:planPrice': number;
      'invoice:company:user:company:MRR': number;
      'invoice:company:user:company:user:id': number;
      'invoice:company:user:company:user:firstname': string;
      'invoice:company:user:company:user:lastname': string;
      'invoice:company:user:company:user:email': string;
      'invoice:company:user:company:user:password': string;
      'invoice:company:user:company:user:avatar': string;
      'invoice:company:user:company:user:role': 'user' | 'editor' | 'admin';
      'invoice:company:user:company:user:status': 'enabled' | 'disabled' | 'deleted';
      'invoice:company:user:company:user:company_id': number;
      'invoice:company:user:company:user:created_at': string;
      'invoice:company:user:company:user:updated_at': string;
      'invoice:company:user:company:user:completed_at': string;
      'invoice:company:user:company:user:Fullname': string;
      'invoice:company:user:company:currentPlan:id': number;
      'invoice:company:user:company:currentPlan:name': string;
      'invoice:company:user:company:currentPlan:price': number;
      'invoice:company:user:company:currentPlan:description': string;
      'invoice:company:user:company:currentPlan:interval': 'monthly' | 'yearly' | 'custom';
      'invoice:company:user:company:currentPlan:created_at': string;
      'invoice:company:user:company:currentPlan:updated_at': string;
      'invoice:company:currentPlan:id': number;
      'invoice:company:currentPlan:name': string;
      'invoice:company:currentPlan:price': number;
      'invoice:company:currentPlan:description': string;
      'invoice:company:currentPlan:interval': 'monthly' | 'yearly' | 'custom';
      'invoice:company:currentPlan:created_at': string;
      'invoice:company:currentPlan:updated_at': string;
      'invoice:subscription:id': number;
      'invoice:subscription:customer_id': number;
      'invoice:subscription:company_id': number;
      'invoice:subscription:plan_id': number;
      'invoice:subscription:started_at': string;
      'invoice:subscription:ended_at': string;
      'invoice:subscription:renewal_date': string;
      'invoice:subscription:discount': number;
      'invoice:subscription:created_at': string;
      'invoice:subscription:updated_at': string;
      'invoice:subscription:commitment': 'monthly' | 'yearly';
      'invoice:subscription:status': 'active' | 'paused' | 'canceled';
      'invoice:subscription:customer:id': number;
      'invoice:subscription:customer:firstname': string;
      'invoice:subscription:customer:lastname': string;
      'invoice:subscription:customer:email': string;
      'invoice:subscription:customer:password': string;
      'invoice:subscription:customer:avatar': string;
      'invoice:subscription:customer:role': 'user' | 'editor' | 'admin';
      'invoice:subscription:customer:status': 'enabled' | 'disabled' | 'deleted';
      'invoice:subscription:customer:company_id': number;
      'invoice:subscription:customer:created_at': string;
      'invoice:subscription:customer:updated_at': string;
      'invoice:subscription:customer:completed_at': string;
      'invoice:subscription:customer:Fullname': string;
      'invoice:subscription:customer:company:id': number;
      'invoice:subscription:customer:company:name': string;
      'invoice:subscription:customer:company:industry': string;
      'invoice:subscription:customer:company:size': number;
      'invoice:subscription:customer:company:created_at': string;
      'invoice:subscription:customer:company:updated_at': string;
      'invoice:subscription:customer:company:user_id': number;
      'invoice:subscription:customer:company:planId': number;
      'invoice:subscription:customer:company:nbUsers': number;
      'invoice:subscription:customer:company:planPrice': number;
      'invoice:subscription:customer:company:MRR': number;
      'invoice:subscription:customer:company:user:id': number;
      'invoice:subscription:customer:company:user:firstname': string;
      'invoice:subscription:customer:company:user:lastname': string;
      'invoice:subscription:customer:company:user:email': string;
      'invoice:subscription:customer:company:user:password': string;
      'invoice:subscription:customer:company:user:avatar': string;
      'invoice:subscription:customer:company:user:role': 'user' | 'editor' | 'admin';
      'invoice:subscription:customer:company:user:status': 'enabled' | 'disabled' | 'deleted';
      'invoice:subscription:customer:company:user:company_id': number;
      'invoice:subscription:customer:company:user:created_at': string;
      'invoice:subscription:customer:company:user:updated_at': string;
      'invoice:subscription:customer:company:user:completed_at': string;
      'invoice:subscription:customer:company:user:Fullname': string;
      'invoice:subscription:customer:company:currentPlan:id': number;
      'invoice:subscription:customer:company:currentPlan:name': string;
      'invoice:subscription:customer:company:currentPlan:price': number;
      'invoice:subscription:customer:company:currentPlan:description': string;
      'invoice:subscription:customer:company:currentPlan:interval': 'monthly' | 'yearly' | 'custom';
      'invoice:subscription:customer:company:currentPlan:created_at': string;
      'invoice:subscription:customer:company:currentPlan:updated_at': string;
      'invoice:subscription:company:id': number;
      'invoice:subscription:company:name': string;
      'invoice:subscription:company:industry': string;
      'invoice:subscription:company:size': number;
      'invoice:subscription:company:created_at': string;
      'invoice:subscription:company:updated_at': string;
      'invoice:subscription:company:user_id': number;
      'invoice:subscription:company:planId': number;
      'invoice:subscription:company:nbUsers': number;
      'invoice:subscription:company:planPrice': number;
      'invoice:subscription:company:MRR': number;
      'invoice:subscription:company:user:id': number;
      'invoice:subscription:company:user:firstname': string;
      'invoice:subscription:company:user:lastname': string;
      'invoice:subscription:company:user:email': string;
      'invoice:subscription:company:user:password': string;
      'invoice:subscription:company:user:avatar': string;
      'invoice:subscription:company:user:role': 'user' | 'editor' | 'admin';
      'invoice:subscription:company:user:status': 'enabled' | 'disabled' | 'deleted';
      'invoice:subscription:company:user:company_id': number;
      'invoice:subscription:company:user:created_at': string;
      'invoice:subscription:company:user:updated_at': string;
      'invoice:subscription:company:user:completed_at': string;
      'invoice:subscription:company:user:Fullname': string;
      'invoice:subscription:company:user:company:id': number;
      'invoice:subscription:company:user:company:name': string;
      'invoice:subscription:company:user:company:industry': string;
      'invoice:subscription:company:user:company:size': number;
      'invoice:subscription:company:user:company:created_at': string;
      'invoice:subscription:company:user:company:updated_at': string;
      'invoice:subscription:company:user:company:user_id': number;
      'invoice:subscription:company:user:company:planId': number;
      'invoice:subscription:company:user:company:nbUsers': number;
      'invoice:subscription:company:user:company:planPrice': number;
      'invoice:subscription:company:user:company:MRR': number;
      'invoice:subscription:company:currentPlan:id': number;
      'invoice:subscription:company:currentPlan:name': string;
      'invoice:subscription:company:currentPlan:price': number;
      'invoice:subscription:company:currentPlan:description': string;
      'invoice:subscription:company:currentPlan:interval': 'monthly' | 'yearly' | 'custom';
      'invoice:subscription:company:currentPlan:created_at': string;
      'invoice:subscription:company:currentPlan:updated_at': string;
      'invoice:subscription:plan:id': number;
      'invoice:subscription:plan:name': string;
      'invoice:subscription:plan:price': number;
      'invoice:subscription:plan:description': string;
      'invoice:subscription:plan:interval': 'monthly' | 'yearly' | 'custom';
      'invoice:subscription:plan:created_at': string;
      'invoice:subscription:plan:updated_at': string;
      'invoice:plan:id': number;
      'invoice:plan:name': string;
      'invoice:plan:price': number;
      'invoice:plan:description': string;
      'invoice:plan:interval': 'monthly' | 'yearly' | 'custom';
      'invoice:plan:created_at': string;
      'invoice:plan:updated_at': string;
    };
  };
  'users': {
    plain: {
      'id': number;
      'firstname': string;
      'lastname': string;
      'email': string;
      'password': string;
      'avatar': string;
      'role': 'user' | 'editor' | 'admin';
      'status': 'enabled' | 'disabled' | 'deleted';
      'company_id': number;
      'created_at': string;
      'updated_at': string;
      'completed_at': string;
      'Fullname': string;
    };
    nested: {
      'company': Schema['companies']['plain'] & Schema['companies']['nested'];
    };
    flat: {
      'company:id': number;
      'company:name': string;
      'company:industry': string;
      'company:size': number;
      'company:created_at': string;
      'company:updated_at': string;
      'company:user_id': number;
      'company:planId': number;
      'company:nbUsers': number;
      'company:planPrice': number;
      'company:MRR': number;
      'company:user:id': number;
      'company:user:firstname': string;
      'company:user:lastname': string;
      'company:user:email': string;
      'company:user:password': string;
      'company:user:avatar': string;
      'company:user:role': 'user' | 'editor' | 'admin';
      'company:user:status': 'enabled' | 'disabled' | 'deleted';
      'company:user:company_id': number;
      'company:user:created_at': string;
      'company:user:updated_at': string;
      'company:user:completed_at': string;
      'company:user:Fullname': string;
      'company:user:company:id': number;
      'company:user:company:name': string;
      'company:user:company:industry': string;
      'company:user:company:size': number;
      'company:user:company:created_at': string;
      'company:user:company:updated_at': string;
      'company:user:company:user_id': number;
      'company:user:company:planId': number;
      'company:user:company:nbUsers': number;
      'company:user:company:planPrice': number;
      'company:user:company:MRR': number;
      'company:user:company:user:id': number;
      'company:user:company:user:firstname': string;
      'company:user:company:user:lastname': string;
      'company:user:company:user:email': string;
      'company:user:company:user:password': string;
      'company:user:company:user:avatar': string;
      'company:user:company:user:role': 'user' | 'editor' | 'admin';
      'company:user:company:user:status': 'enabled' | 'disabled' | 'deleted';
      'company:user:company:user:company_id': number;
      'company:user:company:user:created_at': string;
      'company:user:company:user:updated_at': string;
      'company:user:company:user:completed_at': string;
      'company:user:company:user:Fullname': string;
      'company:user:company:user:company:id': number;
      'company:user:company:user:company:name': string;
      'company:user:company:user:company:industry': string;
      'company:user:company:user:company:size': number;
      'company:user:company:user:company:created_at': string;
      'company:user:company:user:company:updated_at': string;
      'company:user:company:user:company:user_id': number;
      'company:user:company:user:company:planId': number;
      'company:user:company:user:company:nbUsers': number;
      'company:user:company:user:company:planPrice': number;
      'company:user:company:user:company:MRR': number;
      'company:user:company:currentPlan:id': number;
      'company:user:company:currentPlan:name': string;
      'company:user:company:currentPlan:price': number;
      'company:user:company:currentPlan:description': string;
      'company:user:company:currentPlan:interval': 'monthly' | 'yearly' | 'custom';
      'company:user:company:currentPlan:created_at': string;
      'company:user:company:currentPlan:updated_at': string;
      'company:currentPlan:id': number;
      'company:currentPlan:name': string;
      'company:currentPlan:price': number;
      'company:currentPlan:description': string;
      'company:currentPlan:interval': 'monthly' | 'yearly' | 'custom';
      'company:currentPlan:created_at': string;
      'company:currentPlan:updated_at': string;
    };
  };
};
